import { ProfitProduct } from "./profitFilter";

export const SAMPLE_PRODUCTS: ProfitProduct[] = [
  {
    id: "sample-001",
    title: "【新品未開封】ポケモンカードゲーム スカーレット&バイオレット 強化拡張パック ステラミラクル BOX 30パック入り",
    imageUrl: "https://thumbnail.image.rakuten.co.jp/@0_mall/toysrus/cabinet/products/4521329622361.jpg",
    category: "トレカ",
    source: {
      site: "rakuten",
      siteName: "楽天",
      price: 6600,
      url: "https://www.rakuten.co.jp/",
      pointRate: 10,
      pointAmount: 660,
    },
    isNew: true,
    coreKeyword: "ポケモンカード ステラミラクル BOX",
    ebaySoldUrl: "https://www.ebay.com/sch/i.html?_nkw=Pokemon+Card+Stellar+Miracle+BOX&LH_Complete=1&LH_Sold=1",
    realAvgPrice: 18600,
    realProfit: 10140,
    realProfitRate: 154,
    realCount: 47,
  },
  {
    id: "sample-002",
    title: "バンダイ MG 1/100 MSN-04 サザビー Ver.Ka プラモデル ガンプラ",
    imageUrl: "https://thumbnail.image.rakuten.co.jp/@0_mall/amiami/cabinet/products/4573102619808.jpg",
    category: "ガンプラ",
    source: {
      site: "rakuten",
      siteName: "楽天",
      price: 8800,
      url: "https://www.rakuten.co.jp/",
      pointRate: 5,
      pointAmount: 440,
    },
    isNew: false,
    coreKeyword: "MG 1/100 サザビー Ver.Ka",
    ebaySoldUrl: "https://www.ebay.com/sch/i.html?_nkw=MG+1+100+Sazabi+Ver+Ka&LH_Complete=1&LH_Sold=1",
    realAvgPrice: 22480,
    realProfit: 10832,
    realProfitRate: 123,
    realCount: 28,
  },
  {
    id: "sample-003",
    title: "LEGO レゴ テクニック 42171 メルセデス AMG F1 W14 E パフォーマンス",
    imageUrl: "https://thumbnail.image.rakuten.co.jp/@0_mall/toysrus/cabinet/products/5702017583884.jpg",
    category: "LEGO",
    source: {
      site: "rakuten",
      siteName: "楽天",
      price: 34800,
      url: "https://www.rakuten.co.jp/",
      pointRate: 8,
      pointAmount: 2784,
    },
    isNew: false,
    coreKeyword: "LEGO Technic 42171 Mercedes AMG F1",
    ebaySoldUrl: "https://www.ebay.com/sch/i.html?_nkw=LEGO+42171+Mercedes+AMG+F1&LH_Complete=1&LH_Sold=1",
    realAvgPrice: 65200,
    realProfit: 23820,
    realProfitRate: 68,
    realCount: 19,
  },
  {
    id: "sample-004",
    title: "グッドスマイルカンパニー ねんどろいど 初音ミク V4X 初音ミク 公式フィギュア",
    imageUrl: "https://thumbnail.image.rakuten.co.jp/@0_mall/goodsmile/cabinet/products/4580590170957.jpg",
    category: "フィギュア",
    source: {
      site: "rakuten",
      siteName: "楽天",
      price: 6600,
      url: "https://www.rakuten.co.jp/",
      pointRate: 3,
      pointAmount: 198,
    },
    isNew: false,
    coreKeyword: "Nendoroid Hatsune Miku",
    ebaySoldUrl: "https://www.ebay.com/sch/i.html?_nkw=Nendoroid+Hatsune+Miku+V4X&LH_Complete=1&LH_Sold=1",
    realAvgPrice: 14800,
    realProfit: 6540,
    realProfitRate: 99,
    realCount: 35,
  },
  {
    id: "sample-005",
    title: "資生堂 アネッサ パーフェクトUV スキンケアミルク N SPF50+ PA++++ 60mL 日焼け止め",
    imageUrl: "https://thumbnail.image.rakuten.co.jp/@0_mall/shiseido/cabinet/products/4909978199274.jpg",
    category: "コスメ",
    source: {
      site: "rakuten",
      siteName: "楽天",
      price: 2090,
      url: "https://www.rakuten.co.jp/",
      pointRate: 20,
      pointAmount: 418,
    },
    isNew: false,
    coreKeyword: "Shiseido Anessa Perfect UV SPF50+",
    ebaySoldUrl: "https://www.ebay.com/sch/i.html?_nkw=Shiseido+Anessa+Perfect+UV+SPF50&LH_Complete=1&LH_Sold=1",
    realAvgPrice: 5600,
    realProfit: 2470,
    realProfitRate: 118,
    realCount: 62,
  },
  {
    id: "sample-006",
    title: "タカラトミー トミカ ギフトセット 働く車セット 10台入り ミニカー",
    imageUrl: "https://thumbnail.image.rakuten.co.jp/@0_mall/toysrus/cabinet/products/4904810196280.jpg",
    category: "おもちゃ",
    source: {
      site: "rakuten",
      siteName: "楽天",
      price: 3300,
      url: "https://www.rakuten.co.jp/",
      pointRate: 5,
      pointAmount: 165,
    },
    isNew: false,
    coreKeyword: "Tomica Gift Set Working Cars",
    ebaySoldUrl: "https://www.ebay.com/sch/i.html?_nkw=Tomica+Gift+Set+10+cars&LH_Complete=1&LH_Sold=1",
    realAvgPrice: 7200,
    realProfit: 2620,
    realProfitRate: 79,
    realCount: 21,
  },
  {
    id: "sample-007",
    title: "任天堂 Nintendo Switch 本体 (ニンテンドースイッチ) Joy-Con(L) ネオンブルー/(R) ネオンレッド",
    imageUrl: "https://thumbnail.image.rakuten.co.jp/@0_mall/joshin-os/cabinet/45/4902370550436.jpg",
    category: "ゲーム",
    source: {
      site: "rakuten",
      siteName: "楽天",
      price: 32978,
      url: "https://www.rakuten.co.jp/",
      pointRate: 4,
      pointAmount: 1319,
    },
    isNew: true,
    coreKeyword: "Nintendo Switch Joy-Con Neon Blue Red",
    ebaySoldUrl: "https://www.ebay.com/sch/i.html?_nkw=Nintendo+Switch+Neon+Blue+Red&LH_Complete=1&LH_Sold=1",
    realAvgPrice: 54800,
    realProfit: 16542,
    realProfitRate: 50,
    realCount: 88,
  },
  {
    id: "sample-008",
    title: "コトブキヤ 装甲娘 フレームアームズ・ガール スティレット レッドライン Ver. 1/1スケール プラモデル",
    imageUrl: "https://thumbnail.image.rakuten.co.jp/@0_mall/amiami/cabinet/products/4934054026630.jpg",
    category: "フィギュア",
    source: {
      site: "rakuten",
      siteName: "楽天",
      price: 4980,
      url: "https://www.rakuten.co.jp/",
      pointRate: 3,
      pointAmount: 149,
    },
    isNew: false,
    coreKeyword: "Kotobukiya Frame Arms Girl Stiletto",
    ebaySoldUrl: "https://www.ebay.com/sch/i.html?_nkw=Kotobukiya+Frame+Arms+Girl+Stiletto&LH_Complete=1&LH_Sold=1",
    realAvgPrice: 9800,
    realProfit: 3340,
    realProfitRate: 67,
    realCount: 14,
  },
  {
    id: "sample-009",
    title: "セイコー SEIKO 5 スポーツ 自動巻き メンズ 腕時計 SRPD71K1 ブラック",
    imageUrl: "https://thumbnail.image.rakuten.co.jp/@0_mall/seiko/cabinet/products/4954628234865.jpg",
    category: "腕時計",
    source: {
      site: "rakuten",
      siteName: "楽天",
      price: 34100,
      url: "https://www.rakuten.co.jp/",
      pointRate: 6,
      pointAmount: 2046,
    },
    isNew: false,
    coreKeyword: "Seiko 5 Sports SRPD71 Automatic",
    ebaySoldUrl: "https://www.ebay.com/sch/i.html?_nkw=Seiko+5+Sports+SRPD71&LH_Complete=1&LH_Sold=1",
    realAvgPrice: 58000,
    realProfit: 18190,
    realProfitRate: 53,
    realCount: 31,
  },
  {
    id: "sample-010",
    title: "遊戯王OCG デュエルモンスターズ ALLIANCE INSIGHT BOX 1カートン 24BOX入り",
    imageUrl: "https://thumbnail.image.rakuten.co.jp/@0_mall/cardshopgallery/cabinet/products/4988602181890.jpg",
    category: "トレカ",
    source: {
      site: "rakuten",
      siteName: "楽天",
      price: 14400,
      url: "https://www.rakuten.co.jp/",
      pointRate: 8,
      pointAmount: 1152,
    },
    isNew: true,
    coreKeyword: "Yu-Gi-Oh Alliance Insight BOX",
    ebaySoldUrl: "https://www.ebay.com/sch/i.html?_nkw=Yugioh+Alliance+Insight+BOX+Japanese&LH_Complete=1&LH_Sold=1",
    realAvgPrice: 29600,
    realProfit: 12540,
    realProfitRate: 87,
    realCount: 23,
  },
];
