// eBay発掘キーワード（124本）。refresh.mjs(楽天マッチ) と ebaySoldWorker.mjs(Pixel落札発掘) で共有。
// {q: eBay検索語(英), name: 表示/ジャンルキー}。name は guessCategory/EXPECTED_GENRE と対応（refresh.mjs参照）。

// 【ユーザー厳命】関税問題/国際郵便で送れない航空危険物等は絶対にカタログ対象にしない。発掘(worker)と取込(refresh)の双方で除外＝SSOT。
//   明確な危険物ワードに限定（腕時計の「電池/ソーラー」やスプレーボトル等の正常品を巻き込まないよう bareの電池/スプレーは使わない）。
export const PROHIBITED_EXCLUDE = /香水|フレグランス|オードトワレ|オーデコロン|パフューム|perfume|cologne|fragrance|eau de|スプレー缶|エアゾール|エアゾル|ヘアスプレー|制汗スプレー|殺虫スプレー|aerosol|モバイルバッテリー|リチウムイオンバッテリー|power\s?bank|ライター|チャッカマン|lighter|花火|火薬|爆竹|firework|カセットボンベ|ガスボンベ|gas\s?canister|マニキュア|除光液|ネイルリムーバー|nail\s?polish|消毒用アルコール|エタノール|医薬品|劇薬|農薬/i;

export const EBAY_JP_QUERIES = [
  { q: 'pokemon card booster box japanese sealed',  name: 'ポケモンカード' },
  { q: 'yu-gi-oh card booster box japanese sealed',  name: '遊戯王' },
  { q: 'one piece card game booster box japanese',   name: 'ワンピースカード' },
  { q: 'gunpla model kit bandai master grade',       name: 'ガンプラMG' },
  { q: 'gunpla high grade bandai japan new',         name: 'ガンプラHG' },
  { q: 'nendoroid figure good smile new sealed',     name: 'ねんどろいど' },
  { q: 'lego set japan new sealed',                  name: 'LEGO' },
  { q: 'seiko watch new japan',                      name: 'セイコー' },
  { q: 'casio g-shock new japan',                    name: 'Gショック' },
  { q: 'shiseido skincare japan new',                name: '資生堂' },
  { q: 'tomica diecast car japan new',               name: 'トミカ' },
  { q: 'amiibo nintendo new japan sealed',           name: 'アミーボ' },
  { q: 'dragon ball fusion world booster box japanese sealed',                 name: 'DBフュージョンワールド' },
  { q: 'weiss schwarz hololive booster box japanese sealed',                   name: 'ヴァイス ホロライブ' },
  { q: 'digimon card game booster box japanese sealed bandai',                 name: 'デジモンカード' },
  { q: 'amiibo card animal crossing japanese sealed booster',                  name: 'どうぶつの森amiiboカード' },
  { q: 'gundam RG real grade model kit bandai japan new sealed',               name: 'ガンプラRG' },
  { q: 'gundam PG perfect grade unleashed model kit bandai japan new sealed',  name: 'ガンプラPG' },
  { q: 'gundam entry grade EG model kit bandai japan new sealed',              name: 'ガンプラEG' },
  { q: '30MM armored core VI model kit bandai japan new sealed',               name: '30MM ACVI' },
  { q: 's.h.figuarts dragon ball figure japan new sealed',                     name: 'SHFドラゴンボール' },
  { q: 's.h.figuarts demon slayer figure new japan',                          name: 'SHF鬼滅' },
  { q: 'figma figure max factory japan new sealed',                           name: 'figma' },
  { q: 'pop up parade figure good smile new japan',                           name: 'POP UP PARADE' },
  { q: 'metal build gundam bandai figure japan new sealed',                    name: 'METAL BUILD' },
  { q: 'kotobukiya megami device frame arms girl model kit japan new sealed',  name: 'メガミ/FAガール' },
  { q: 'casio oceanus watch japan new',                                       name: 'オシアナス' },
  { q: 'citizen attesa eco-drive radio watch japan new',                       name: 'アテッサ' },
  { q: 'orient bambino automatic watch japan new',                            name: 'オリエント バンビーノ' },
  { q: 'anessa perfect uv sunscreen spf50 japan new',                         name: 'アネッサ' },
  { q: 'hada labo gokujyun lotion japan new sealed',                          name: 'ハダラボ極潤' },
  { q: 'canmake makeup japan new sealed',                                     name: 'キャンメイク' },
  { q: 'sk-ii facial treatment essence japan new sealed',                      name: 'SK-II' },
  { q: 'beyblade x takara tomy booster japan new sealed',                      name: 'ベイブレードX' },
  { q: 'tamiya mini 4wd model kit japan new sealed',                          name: 'ミニ四駆' },
  { q: 'pokemon center plush japan exclusive new with tag',                    name: 'ポケセンぬいぐるみ' },
  { q: 'pokemon card 151 booster box japanese sealed sv2a',                      name: 'ポケカ151' },
  { q: 'pokemon card elite trainer box japanese sealed',                        name: 'ポケカETB' },
  { q: 'pokemon card high class pack shiny treasure japanese sealed box',        name: 'ポケカハイクラス' },
  { q: 'yu-gi-oh structure deck japanese sealed konami',                        name: '遊戯王ストラク' },
  { q: 'one piece card game starter deck japanese sealed bandai',                name: 'ワンピーススタートデッキ' },
  { q: 'union arena booster box japanese sealed bandai',                         name: 'ユニオンアリーナ' },
  { q: 's.h.figuarts dragon ball son goku super saiyan figure japan new sealed', name: 'SHF悟空' },
  { q: 's.h.figuarts one piece monkey d luffy figure japan new sealed',          name: 'SHFルフィ' },
  { q: 's.h.figuarts naruto uzumaki figure japan new sealed',                    name: 'SHFナルト' },
  { q: 's.h.figuarts kamen rider figure japan new sealed',                       name: 'SHF仮面ライダー' },
  { q: 'nendoroid hatsune miku figure good smile japan new sealed',              name: 'ねんどミク' },
  { q: 'good smile company 1/7 scale figure anime japan new sealed',             name: 'GSC1/7スケール' },
  { q: 'casio g-shock GA-2100 carbon core guard japan new',                      name: 'GショックGA2100' },
  { q: 'casio g-shock DW-5600 japan new',                                        name: 'GショックDW5600' },
  { q: 'seiko 5 sports SRPD automatic watch japan new',                          name: 'セイコー5SRPD' },
  { q: 'seiko prospex turtle SRPE diver automatic watch japan new',              name: 'セイコープロスペックスSRPE' },
  { q: 'splatoon 3 nintendo switch japanese version new sealed',                 name: 'スプラ3SW' },
  { q: 'xenoblade chronicles 3 nintendo switch japanese version new sealed',     name: 'ゼノブレ3SW' },
  { q: 'chiikawa plush japan new with tag',                                      name: 'ちいかわぬいぐるみ' },
  { q: 'transformers takara tomy masterpiece figure japan new sealed',           name: 'TFマスターピース' },
  { q: 'soul of chogokin bandai diecast figure japan new sealed',                name: '超合金魂' },
  { q: 'seiko presage automatic watch japan new',                                name: 'セイコープレザージュ' },
  { q: 'seiko prospex samurai diver automatic watch japan new',                  name: 'プロスペックスサムライ' },
  { q: 'seiko prospex alpinist automatic watch japan new',                       name: 'プロスペックスアルピニスト' },
  { q: 'seiko prospex speedtimer chronograph watch japan new',                   name: 'プロスペックススピードタイマー' },
  { q: 'seiko 5 sports GMT automatic watch japan new',                           name: 'セイコー5GMT' },
  { q: 'seiko selection solar watch japan new',                                  name: 'セイコーセレクション' },
  { q: 'casio edifice chronograph watch japan new',                              name: 'カシオエディフィス' },
  { q: 'casio pro trek solar watch japan new',                                   name: 'カシオプロトレック' },
  { q: 'casio g-shock GW-M5610 tough solar watch japan new',                     name: 'GショックGWM5610' },
  { q: 'casio g-shock mudmaster watch japan new',                                name: 'Gショックマッドマスター' },
  { q: 'citizen promaster eco-drive diver watch japan new',                      name: 'シチズンプロマスター' },
  { q: 'citizen tsuyosa automatic watch japan new',                             name: 'シチズンTSUYOSA' },
  { q: 'citizen series 8 automatic watch japan new',                            name: 'シチズンシリーズ8' },
  { q: 'orient star automatic watch japan new',                                 name: 'オリエントスター' },
  { q: 'orient kamasu diver automatic watch japan new',                         name: 'オリエントカマス' },
  { q: 'orient mako diver automatic watch japan new',                           name: 'オリエントマコ' },
  { q: 'magic the gathering japanese booster box sealed',                     name: 'MTG日本語' },
  { q: 'cardfight vanguard booster box japanese sealed',                      name: 'ヴァンガード' },
  { q: 'duel masters booster box japanese sealed',                            name: 'デュエマ' },
  { q: 'battle spirits booster box japanese sealed bandai',                   name: 'バトスピ' },
  { q: 'shadowverse evolve booster box japanese sealed',                      name: 'シャドバエボルヴ' },
  { q: 'pokemon card scarlet violet booster box japanese sealed',             name: 'ポケカSV' },
  { q: 'one piece card game OP booster box japanese sealed bandai',           name: 'ワンピOPブースター' },
  { q: 'yu-gi-oh quarter century bonanza booster box japanese sealed',        name: '遊戯王QC' },
  { q: 'robot spirits bandai gundam figure japan new sealed',                 name: 'ROBOT魂' },
  { q: 'mafex medicom toy figure japan new sealed',                           name: 'MAFEX' },
  { q: 'kotobukiya artfx j figure japan new sealed',                          name: 'ARTFX' },
  { q: 'figuarts zero figure bandai japan new sealed',                        name: 'フィギュアーツZERO' },
  { q: 'revoltech kaiyodo figure japan new sealed',                           name: 'リボルテック' },
  { q: 're-ment miniature figure japan new sealed',                          name: 'リーメント' },
  { q: 'nendoroid doll good smile figure japan new sealed',                   name: 'ねんどろいどどーる' },
  { q: 'soul of chogokin bandai diecast robot japan new sealed',              name: '超合金GX' },
  { q: 'legend of zelda tears of the kingdom switch japanese new sealed',      name: 'ゼルダTOTK' },
  { q: 'super mario bros wonder switch japanese new sealed',                   name: 'マリオワンダー' },
  { q: 'pokemon scarlet violet switch japanese new sealed',                    name: 'ポケモンSVソフト' },
  { q: 'super smash bros ultimate switch japanese new sealed',                 name: 'スマブラSP' },
  { q: 'mario kart 8 deluxe switch japanese new sealed',                       name: 'マリカ8DX' },
  { q: 'tamiya 1/24 sports car model kit japan new sealed',                   name: 'タミヤ車' },
  { q: 'tamiya 1/35 military tank model kit japan new sealed',                name: 'タミヤミリタリー' },
  { q: 'tamiya 1/12 motorcycle model kit japan new sealed',                   name: 'タミヤバイク' },
  { q: 'hasegawa 1/48 aircraft model kit japan new sealed',                   name: 'ハセガワ飛行機' },
  { q: 'hasegawa 1/350 ship model kit japan new sealed',                      name: 'ハセガワ船' },
  { q: 'aoshima 1/24 car model kit japan new sealed',                         name: 'アオシマ車' },
  { q: 'fujimi 1/24 car model kit japan new sealed',                          name: 'フジミ車' },
  { q: 'kato n gauge shinkansen model train japan new',                       name: 'KATO新幹線' },
  { q: 'tomix n gauge train set japan new',                                   name: 'TOMIX電車' },
  { q: 'kato n gauge locomotive japan new',                                   name: 'KATO機関車' },
  { q: 'tomix n gauge limited japan new sealed',                              name: 'TOMIX限定' },
  { q: 'kato ho gauge model train japan new',                                 name: 'KATO HO' },
  { q: 'tomica premium diecast car japan new sealed',                         name: 'トミカプレミアム' },
  { q: 'kyosho 1/18 diecast car model japan new',                             name: '京商ミニカー' },
  { q: 'ignition model 1/18 diecast car japan new',                          name: 'イグニッション' },
  { q: 'tomica limited vintage neo diecast japan new',                        name: 'トミカLV NEO' },
  { q: 'hot wheels japan exclusive diecast car new',                          name: 'ホットウィール日本' },
  { q: 'pilot custom 74 fountain pen japan new',                              name: 'パイロットカスタム74' },
  { q: 'pilot capless vanishing point fountain pen japan new',                name: 'パイロットキャップレス' },
  { q: 'sailor 1911 pro gear fountain pen japan new',                         name: 'セーラー万年筆' },
  { q: 'platinum 3776 century fountain pen japan new',                        name: 'プラチナ3776' },
  { q: 'pilot kakuno fountain pen japan new',                                 name: 'パイロットカクノ' },
  { q: 'sanrio plush japan new with tag',                                     name: 'サンリオぬいぐるみ' },
  { q: 'sumikko gurashi plush japan new with tag',                            name: 'すみっコぐらし' },
  { q: 'pokemon center plush japan new with tag',                             name: 'ポケモンぬいぐるみ2' },
  { q: 'studio ghibli totoro plush japan new with tag',                       name: 'ジブリぬいぐるみ' },
  { q: 'chiikawa goods mascot japan new',                                     name: 'ちいかわグッズ' },
  { q: 'refa carat beauty roller japan new',                                  name: 'ReFaカラット' },
  { q: 'refa s carat ray beauty roller japan new',                           name: 'ReFa' },
];
