// eBay発掘キーワード（305本）。refresh.mjs(楽天マッチ) と ebaySoldWorker.mjs(Pixel落札発掘) で共有。
// {q: eBay検索語(英), name: 表示/ジャンルキー}。name は guessCategory/EXPECTED_GENRE と対応（refresh.mjs参照）。

// 【ユーザー厳命】関税問題/国際郵便で送れない航空危険物等は絶対にカタログ対象にしない。発掘(worker)と取込(refresh)の双方で除外＝SSOT。
//   明確な危険物ワードに限定（腕時計の「電池/ソーラー」やスプレーボトル等の正常品を巻き込まないよう bareの電池/スプレーは使わない）。
export const PROHIBITED_EXCLUDE = /香水|フレグランス|オードトワレ|オーデコロン|パフューム|perfume|cologne|fragrance|eau de|スプレー缶|エアゾール|エアゾル|ヘアスプレー|制汗スプレー|殺虫スプレー|aerosol|モバイルバッテリー|リチウムイオンバッテリー|power\s?bank|ライター|チャッカマン|lighter|花火|火薬|爆竹|firework|カセットボンベ|ガスボンベ|gas\s?canister|マニキュア|除光液|ネイルリムーバー|nail\s?polish|消毒用アルコール|エタノール|医薬品|劇薬|農薬/i;

export const EBAY_JP_QUERIES = [
  { q: 'pokemon card booster box japanese sealed',  name: 'ポケモンカード' },
  { q: 'yu-gi-oh card booster box japanese sealed',  name: '遊戯王' },
  { q: 'one piece card game booster box japanese',   name: 'ワンピースカード' },
  { q: 'gunpla model kit bandai master grade',       name: 'ガンプラMG' },
  { q: 'gunpla high grade bandai japan new',         name: 'ガンプラHG' },
  { q: 'nendoroid figure good smile new sealed',     name: 'ねんどろいど' },
  { q: 'lego set japan new sealed',                  name: 'LEGO' },
  { q: 'seiko watch new japan',                      name: 'セイコー' },
  { q: 'casio g-shock new japan',                    name: 'Gショック' },
  { q: 'shiseido skincare japan new',                name: '資生堂' },
  { q: 'tomica diecast car japan new',               name: 'トミカ' },
  { q: 'amiibo nintendo new japan sealed',           name: 'アミーボ' },
  { q: 'dragon ball fusion world booster box japanese sealed',                 name: 'DBフュージョンワールド' },
  { q: 'weiss schwarz hololive booster box japanese sealed',                   name: 'ヴァイス ホロライブ' },
  { q: 'digimon card game booster box japanese sealed bandai',                 name: 'デジモンカード' },
  { q: 'amiibo card animal crossing japanese sealed booster',                  name: 'どうぶつの森amiiboカード' },
  { q: 'gundam RG real grade model kit bandai japan new sealed',               name: 'ガンプラRG' },
  { q: 'gundam PG perfect grade unleashed model kit bandai japan new sealed',  name: 'ガンプラPG' },
  { q: 'gundam entry grade EG model kit bandai japan new sealed',              name: 'ガンプラEG' },
  { q: '30MM armored core VI model kit bandai japan new sealed',               name: '30MM ACVI' },
  { q: 's.h.figuarts dragon ball figure japan new sealed',                     name: 'SHFドラゴンボール' },
  { q: 's.h.figuarts demon slayer figure new japan',                          name: 'SHF鬼滅' },
  { q: 'figma figure max factory japan new sealed',                           name: 'figma' },
  { q: 'pop up parade figure good smile new japan',                           name: 'POP UP PARADE' },
  { q: 'metal build gundam bandai figure japan new sealed',                    name: 'METAL BUILD' },
  { q: 'kotobukiya megami device frame arms girl model kit japan new sealed',  name: 'メガミ/FAガール' },
  { q: 'casio oceanus watch japan new',                                       name: 'オシアナス' },
  { q: 'citizen attesa eco-drive radio watch japan new',                       name: 'アテッサ' },
  { q: 'orient bambino automatic watch japan new',                            name: 'オリエント バンビーノ' },
  { q: 'anessa perfect uv sunscreen spf50 japan new',                         name: 'アネッサ' },
  { q: 'hada labo gokujyun lotion japan new sealed',                          name: 'ハダラボ極潤' },
  { q: 'canmake makeup japan new sealed',                                     name: 'キャンメイク' },
  { q: 'sk-ii facial treatment essence japan new sealed',                      name: 'SK-II' },
  { q: 'beyblade x takara tomy booster japan new sealed',                      name: 'ベイブレードX' },
  { q: 'tamiya mini 4wd model kit japan new sealed',                          name: 'ミニ四駆' },
  { q: 'pokemon center plush japan exclusive new with tag',                    name: 'ポケセンぬいぐるみ' },
  { q: 'pokemon card 151 booster box japanese sealed sv2a',                      name: 'ポケカ151' },
  { q: 'pokemon card elite trainer box japanese sealed',                        name: 'ポケカETB' },
  { q: 'pokemon card high class pack shiny treasure japanese sealed box',        name: 'ポケカハイクラス' },
  { q: 'yu-gi-oh structure deck japanese sealed konami',                        name: '遊戯王ストラク' },
  { q: 'one piece card game starter deck japanese sealed bandai',                name: 'ワンピーススタートデッキ' },
  { q: 'union arena booster box japanese sealed bandai',                         name: 'ユニオンアリーナ' },
  { q: 's.h.figuarts dragon ball son goku super saiyan figure japan new sealed', name: 'SHF悟空' },
  { q: 's.h.figuarts one piece monkey d luffy figure japan new sealed',          name: 'SHFルフィ' },
  { q: 's.h.figuarts naruto uzumaki figure japan new sealed',                    name: 'SHFナルト' },
  { q: 's.h.figuarts kamen rider figure japan new sealed',                       name: 'SHF仮面ライダー' },
  { q: 'nendoroid hatsune miku figure good smile japan new sealed',              name: 'ねんどミク' },
  { q: 'good smile company 1/7 scale figure anime japan new sealed',             name: 'GSC1/7スケール' },
  { q: 'casio g-shock GA-2100 carbon core guard japan new',                      name: 'GショックGA2100' },
  { q: 'casio g-shock DW-5600 japan new',                                        name: 'GショックDW5600' },
  { q: 'seiko 5 sports SRPD automatic watch japan new',                          name: 'セイコー5SRPD' },
  { q: 'seiko prospex turtle SRPE diver automatic watch japan new',              name: 'セイコープロスペックスSRPE' },
  { q: 'splatoon 3 nintendo switch japanese version new sealed',                 name: 'スプラ3SW' },
  { q: 'xenoblade chronicles 3 nintendo switch japanese version new sealed',     name: 'ゼノブレ3SW' },
  { q: 'chiikawa plush japan new with tag',                                      name: 'ちいかわぬいぐるみ' },
  { q: 'transformers takara tomy masterpiece figure japan new sealed',           name: 'TFマスターピース' },
  { q: 'soul of chogokin bandai diecast figure japan new sealed',                name: '超合金魂' },
  { q: 'seiko presage automatic watch japan new',                                name: 'セイコープレザージュ' },
  { q: 'seiko prospex samurai diver automatic watch japan new',                  name: 'プロスペックスサムライ' },
  { q: 'seiko prospex alpinist automatic watch japan new',                       name: 'プロスペックスアルピニスト' },
  { q: 'seiko prospex speedtimer chronograph watch japan new',                   name: 'プロスペックススピードタイマー' },
  { q: 'seiko 5 sports GMT automatic watch japan new',                           name: 'セイコー5GMT' },
  { q: 'seiko selection solar watch japan new',                                  name: 'セイコーセレクション' },
  { q: 'casio edifice chronograph watch japan new',                              name: 'カシオエディフィス' },
  { q: 'casio pro trek solar watch japan new',                                   name: 'カシオプロトレック' },
  { q: 'casio g-shock GW-M5610 tough solar watch japan new',                     name: 'GショックGWM5610' },
  { q: 'casio g-shock mudmaster watch japan new',                                name: 'Gショックマッドマスター' },
  { q: 'citizen promaster eco-drive diver watch japan new',                      name: 'シチズンプロマスター' },
  { q: 'citizen tsuyosa automatic watch japan new',                             name: 'シチズンTSUYOSA' },
  { q: 'citizen series 8 automatic watch japan new',                            name: 'シチズンシリーズ8' },
  { q: 'orient star automatic watch japan new',                                 name: 'オリエントスター' },
  { q: 'orient kamasu diver automatic watch japan new',                         name: 'オリエントカマス' },
  { q: 'orient mako diver automatic watch japan new',                           name: 'オリエントマコ' },
  { q: 'magic the gathering japanese booster box sealed',                     name: 'MTG日本語' },
  { q: 'cardfight vanguard booster box japanese sealed',                      name: 'ヴァンガード' },
  { q: 'duel masters booster box japanese sealed',                            name: 'デュエマ' },
  { q: 'battle spirits booster box japanese sealed bandai',                   name: 'バトスピ' },
  { q: 'shadowverse evolve booster box japanese sealed',                      name: 'シャドバエボルヴ' },
  { q: 'pokemon card scarlet violet booster box japanese sealed',             name: 'ポケカSV' },
  { q: 'one piece card game OP booster box japanese sealed bandai',           name: 'ワンピOPブースター' },
  { q: 'yu-gi-oh quarter century bonanza booster box japanese sealed',        name: '遊戯王QC' },
  { q: 'robot spirits bandai gundam figure japan new sealed',                 name: 'ROBOT魂' },
  { q: 'mafex medicom toy figure japan new sealed',                           name: 'MAFEX' },
  { q: 'kotobukiya artfx j figure japan new sealed',                          name: 'ARTFX' },
  { q: 'figuarts zero figure bandai japan new sealed',                        name: 'フィギュアーツZERO' },
  { q: 'revoltech kaiyodo figure japan new sealed',                           name: 'リボルテック' },
  { q: 're-ment miniature figure japan new sealed',                          name: 'リーメント' },
  { q: 'nendoroid doll good smile figure japan new sealed',                   name: 'ねんどろいどどーる' },
  { q: 'soul of chogokin bandai diecast robot japan new sealed',              name: '超合金GX' },
  { q: 'legend of zelda tears of the kingdom switch japanese new sealed',      name: 'ゼルダTOTK' },
  { q: 'super mario bros wonder switch japanese new sealed',                   name: 'マリオワンダー' },
  { q: 'pokemon scarlet violet switch japanese new sealed',                    name: 'ポケモンSVソフト' },
  { q: 'super smash bros ultimate switch japanese new sealed',                 name: 'スマブラSP' },
  { q: 'mario kart 8 deluxe switch japanese new sealed',                       name: 'マリカ8DX' },
  { q: 'tamiya 1/24 sports car model kit japan new sealed',                   name: 'タミヤ車' },
  { q: 'tamiya 1/35 military tank model kit japan new sealed',                name: 'タミヤミリタリー' },
  { q: 'tamiya 1/12 motorcycle model kit japan new sealed',                   name: 'タミヤバイク' },
  { q: 'hasegawa 1/48 aircraft model kit japan new sealed',                   name: 'ハセガワ飛行機' },
  { q: 'hasegawa 1/350 ship model kit japan new sealed',                      name: 'ハセガワ船' },
  { q: 'aoshima 1/24 car model kit japan new sealed',                         name: 'アオシマ車' },
  { q: 'fujimi 1/24 car model kit japan new sealed',                          name: 'フジミ車' },
  { q: 'kato n gauge shinkansen model train japan new',                       name: 'KATO新幹線' },
  { q: 'tomix n gauge train set japan new',                                   name: 'TOMIX電車' },
  { q: 'kato n gauge locomotive japan new',                                   name: 'KATO機関車' },
  { q: 'tomix n gauge limited japan new sealed',                              name: 'TOMIX限定' },
  { q: 'kato ho gauge model train japan new',                                 name: 'KATO HO' },
  { q: 'tomica premium diecast car japan new sealed',                         name: 'トミカプレミアム' },
  { q: 'kyosho 1/18 diecast car model japan new',                             name: '京商ミニカー' },
  { q: 'ignition model 1/18 diecast car japan new',                          name: 'イグニッション' },
  { q: 'tomica limited vintage neo diecast japan new',                        name: 'トミカLV NEO' },
  { q: 'hot wheels japan exclusive diecast car new',                          name: 'ホットウィール日本' },
  { q: 'pilot custom 74 fountain pen japan new',                              name: 'パイロットカスタム74' },
  { q: 'pilot capless vanishing point fountain pen japan new',                name: 'パイロットキャップレス' },
  { q: 'sailor 1911 pro gear fountain pen japan new',                         name: 'セーラー万年筆' },
  { q: 'platinum 3776 century fountain pen japan new',                        name: 'プラチナ3776' },
  { q: 'pilot kakuno fountain pen japan new',                                 name: 'パイロットカクノ' },
  { q: 'sanrio plush japan new with tag',                                     name: 'サンリオぬいぐるみ' },
  { q: 'sumikko gurashi plush japan new with tag',                            name: 'すみっコぐらし' },
  { q: 'pokemon center plush japan new with tag',                             name: 'ポケモンぬいぐるみ2' },
  { q: 'studio ghibli totoro plush japan new with tag',                       name: 'ジブリぬいぐるみ' },
  { q: 'chiikawa goods mascot japan new',                                     name: 'ちいかわグッズ' },
  { q: 'refa carat beauty roller japan new',                                  name: 'ReFaカラット' },
  { q: 'refa s carat ray beauty roller japan new',                           name: 'ReFa' },

  // ── キーワード拡張(高回転×楽天×非危険物・8カテゴリ並列生成→重複/危険物除外して追記・2026-06-25)。
  { q: 'pokemon japanese terastal festival sv8a booster box sealed', name: 'ポケカ テラスタルフェス' },
  { q: 'pokemon japanese mega evolution booster box sealed new', name: 'ポケカ メガエボリューション' },
  { q: 'pokemon japanese mega brave mega symphonia booster box', name: 'ポケカ メガブレイブ/シンフォニア' },
  { q: 'pokemon japanese black bolt white flare booster box sealed', name: 'ポケカ ブラックボルト/ホワイトフレア' },
  { q: 'yugioh quarter century bonanza booster box japanese sealed', name: '遊戯王 QCバランザ' },
  { q: 'yugioh rarity collection quarter century edition japanese box', name: '遊戯王 レアリティコレクションQC' },
  { q: 'yugioh structure deck japanese new sealed', name: '遊戯王 ストラクチャーデッキ' },
  { q: 'one piece card op12 legacy of the master booster box japanese', name: 'ワンピOP12 マスターの背中' },
  { q: 'one piece card op13 carrying on his will booster box japanese', name: 'ワンピOP13 受け継がれる意志' },
  { q: 'one piece card premium booster japanese sealed new', name: 'ワンピ プレミアムブースター' },
  { q: 'cardfight vanguard divinez booster box japanese sealed', name: 'ヴァンガード ディヴァインズ' },
  { q: 'cardfight vanguard crimson moon dz-bt14 booster box japan', name: 'ヴァンガード 真紅の月BT14' },
  { q: 'shadowverse evolve booster box japanese sealed new', name: 'シャドバ エボルヴ' },
  { q: 'duel masters booster pack japanese sealed new', name: 'デュエマ ブースターパック' },
  { q: 'battle spirits booster pack japanese sealed new', name: 'バトスピ ブースターパック' },
  { q: 'build divide booster box japanese tcg sealed', name: 'ビルディバイド' },
  { q: 'gundam card game booster box japanese sealed new', name: 'ガンダムカードゲーム' },
  { q: 'zx zillions of enemy x booster pack japanese sealed', name: 'Z/X ゼクス' },
  { q: 'bushiroad sleeve collection hg japanese card sleeves new', name: 'ブシロード スリーブHG' },
  { q: 'pokemon center japan deck case card case new sealed', name: 'ポケセン デッキケース' },
  { q: 'pokemon japanese deck shield card sleeves 64 new sealed', name: 'ポケカ 公式デッキシールド' },
  { q: 'yugioh card case duelist card protector japanese new', name: '遊戯王 カードケース' },
  { q: 'japanese tcg storage box card deck holder pokemon new', name: '日本TCG収納ボックス' },
  { q: 'one piece card game official sleeve japanese new sealed', name: 'ワンピカード 公式スリーブ' },
  { q: 'ichiban kuji one piece figure japan', name: '一番くじワンピース' },
  { q: 'ichiban kuji dragon ball figure japan', name: '一番くじドラゴンボール' },
  { q: 'ichiban kuji demon slayer figure japan', name: '一番くじ鬼滅' },
  { q: 'ichiban kuji jujutsu kaisen figure japan', name: '一番くじ呪術廻戦' },
  { q: 'ichiban kuji chainsaw man figure japan', name: '一番くじチェンソーマン' },
  { q: 'banpresto grandista figure japan', name: 'グランディスタ' },
  { q: 'banpresto ichiban kuji last one prize figure', name: 'ラストワン賞フィギュア' },
  { q: 'sega prize figure spm japan', name: 'セガSPMフィギュア' },
  { q: 'taito prize figure coreful japan', name: 'タイトーコアフル' },
  { q: 'furyu noodle stopper figure japan', name: 'フリューぬーどるストッパー' },
  { q: 're-ment miniature japan new', name: 'リーメントぷちサンプル' },
  { q: 're-ment sanrio miniature japan', name: 'リーメントサンリオ' },
  { q: 're-ment pokemon miniature japan', name: 'リーメントポケモン' },
  { q: 'shokugan candy toy figure japan', name: '食玩フィギュア' },
  { q: 'bandai shodo figure japan', name: 'SHODO食玩' },
  { q: 'gashapon capsule toy japan', name: 'ガチャ/カプセルトイ' },
  { q: 'bandai gunpla gashapon mobile suit ensemble', name: '機動戦士アンサンブル' },
  { q: 'qposket disney princess figure japan', name: 'Qposketディズニー' },
  { q: 'qposket dragon ball figure japan', name: 'QposketドラゴンボールZ' },
  { q: 'nakayoshi tirol mascot capsule japan', name: 'ご当地ガチャマスコット' },
  { q: 'ichiban kuji spy family figure japan', name: '一番くじスパイファミリー' },
  { q: 'banpresto relax time figure japan', name: 'リラックスタイムフィギュア' },
  { q: 'megahouse lookup figure japan', name: 'ルックアップシリーズ' },
  { q: 'Tamiya 1/24 Skyline GT-R model kit japan', name: 'タミヤ1/24スカイラインGT-R' },
  { q: 'Tamiya 1/24 Toyota Supra model kit japan', name: 'タミヤ1/24スープラ' },
  { q: 'Tamiya 1/24 sports car series new sealed japan', name: 'タミヤ1/24スポーツカーシリーズ' },
  { q: 'Tamiya 1/35 military tank model kit japan', name: 'タミヤ1/35ミリタリーミニチュア' },
  { q: 'Tamiya 1/12 motorcycle model kit japan', name: 'タミヤ1/12バイク' },
  { q: 'Tamiya 1/700 waterline ship model kit japan', name: 'タミヤ1/700ウォーターライン艦船' },
  { q: 'Hasegawa 1/72 aircraft model kit japan new', name: 'ハセガワ1/72航空機' },
  { q: 'Hasegawa 1/48 fighter jet model kit japan', name: 'ハセガワ1/48ジェット戦闘機' },
  { q: 'Hasegawa egg plane model kit japan', name: 'ハセガワたまごひこーき' },
  { q: 'Fujimi 1/700 ship model kit japan', name: 'フジミ1/700艦船' },
  { q: 'Aoshima 1/24 tuned car model kit japan', name: 'アオシマ1/24ザ・チューンドカー' },
  { q: 'Aoshima Initial D model kit 1/24 japan', name: 'アオシマ頭文字D' },
  { q: 'Aoshima 1/32 truck model kit japan dekotora', name: 'アオシマ1/32トラック野郎/デコトラ' },
  { q: 'Bandai 30MS option body parts model kit', name: '30MSオプションボディパーツ' },
  { q: 'Robot Spirits gundam action figure japan new', name: 'ロボット魂ガンダム' },
  { q: 'Bandai HGUC Zaku gunpla model kit japan', name: 'HGUCザク' },
  { q: 'Bandai HGUC Sazabi Nu Gundam model kit', name: 'HGUCサザビー/νガンダム' },
  { q: 'Bandai HG Gundam Aerial witch from mercury kit', name: 'HGエアリアル' },
  { q: 'Bandai Full Mechanics gundam model kit japan', name: 'フルメカニクスガンダム' },
  { q: 'Wave 1/20 maschinen krieger model kit japan', name: 'ウェーブ マシーネンクリーガー' },
  { q: 'Hasegawa creator works VF Macron model kit', name: 'ハセガワ マクロスVF' },
  { q: 'Kotobukiya Frame Arms model kit japan new', name: 'コトブキヤ フレームアームズ' },
  { q: 'Tamiya 1/24 Mazda RX-7 model kit japan', name: 'タミヤ1/24RX-7' },
  { q: 'Pokemon Legends Z-A Switch 2 japanese version new sealed', name: 'ポケモンZ-A日本版' },
  { q: 'Pokemon Scarlet Violet switch japanese version sealed', name: 'ポケモンSV日本版' },
  { q: 'Pokemon Pokopia switch 2 japanese new sealed', name: 'ポケピア日本版' },
  { q: 'Dragon Quest VII Reimagined switch 2 japanese sealed', name: 'DQ7リメイク日本版' },
  { q: 'Final Fantasy VII switch 2 japanese version sealed', name: 'FF7Switch日本版' },
  { q: 'Monster Hunter Stories 3 switch japanese sealed', name: 'MHストーリーズ3日本版' },
  { q: 'Famicom Detective Club switch japanese new sealed', name: 'ファミ探日本版' },
  { q: 'Super Mario Party Jamboree switch japanese sealed', name: 'マリパJ日本版' },
  { q: 'Kirby Air Riders switch 2 japanese version sealed', name: 'カービィエアライダー日本版' },
  { q: 'Mario Kart World switch 2 japanese version sealed', name: 'マリカワールド日本版' },
  { q: 'Donkey Kong Bananza switch 2 japanese sealed', name: 'DKバナンザ日本版' },
  { q: 'Atelier Yumia switch japanese version sealed', name: 'アトリエ日本版' },
  { q: 'Romancing SaGa switch japanese version new sealed', name: 'ロマサガ日本版' },
  { q: 'Hori split pad pro nintendo switch japanese new', name: 'Horiスプリットパッド' },
  { q: 'Hori split pad compact nintendo switch japanese new', name: 'Horiスプリットパッドコンパクト' },
  { q: 'Nintendo switch 2 pro controller japanese version new', name: 'Switch2プロコン日本版' },
  { q: 'Hori grip controller nintendo switch wired japanese new', name: 'Hori有線グリコン' },
  { q: 'Nintendo switch 2 carrying case japanese official new', name: 'Switch2純正ケース' },
  { q: 'Hori screen protector filter nintendo switch 2 japanese', name: 'Hori液晶保護フィルム' },
  { q: 'Nintendo switch 2 joy-con strap colored japanese new', name: 'ジョイコンストラップ日本版' },
  { q: 'Famicom mini classic console nintendo japanese new', name: 'ミニファミコン' },
  { q: 'Hori pokemon nintendo switch case pouch japanese new', name: 'Horiポケモンポーチ' },
  { q: 'Nintendo switch 2 dock set japanese official new', name: 'Switch2ドックセット日本版' },
  { q: 'Game Boy classic mini reissue nintendo japanese new', name: '復刻ゲームボーイ周辺' },
  { q: 'Seiko 5 Sports SSK GMT automatic japan', name: 'セイコー5GMT SSK' },
  { q: 'Seiko 5 Sports SRPK automatic japan new', name: 'セイコー5スポーツSRPK' },
  { q: 'Seiko Presage cocktail time automatic japan', name: 'プレザージュ カクテルタイム' },
  { q: 'Seiko Prospex Speedtimer solar chronograph SSC japan', name: 'プロスペックス スピードタイマー' },
  { q: 'Seiko Alpinist SPB121 green automatic japan', name: 'セイコー アルピニスト SPB121' },
  { q: 'Seiko Prospex Sumo SPB diver automatic japan', name: 'プロスペックス スモウ' },
  { q: 'Seiko Prospex Tuna solar diver japan', name: 'プロスペックス ツナ缶' },
  { q: 'Casio G-Shock GM-B2100 full metal japan', name: 'Gショック フルメタルB2100' },
  { q: 'Casio G-Shock MTG-B3000 MT-G metal japan', name: 'Gショック MT-G B3000' },
  { q: 'Casio G-Shock GM-2100 metal bezel japan', name: 'Gショック メタルベゼルGM2100' },
  { q: 'Casio G-Shock GA-B2100 tough solar bluetooth japan', name: 'Gショック GA-B2100ソーラー' },
  { q: 'Casio vintage A168WG gold digital japan', name: 'カシオ ヴィンテージ金A168' },
  { q: 'Casio vintage A158WA silver digital japan', name: 'カシオ ヴィンテージ銀A158' },
  { q: 'Casio Pro Trek PRG-340 solar triple sensor japan', name: 'プロトレック PRG-340' },
  { q: 'Casio Pro Trek PRW-3500 solar atomic japan', name: 'プロトレック PRW-3500' },
  { q: 'Casio Edifice EQB chronograph solar bluetooth japan', name: 'エディフィス EQBソーラー' },
  { q: 'Citizen Promaster diver BN0150 eco-drive japan', name: 'シチズン プロマスターBN0150' },
  { q: 'Citizen Tsuyosa NJ0150 automatic japan', name: 'シチズン ツヨサ NJ0150' },
  { q: 'Citizen Promaster Sky JY8078 pilot eco-drive japan', name: 'プロマスタースカイ JY8078' },
  { q: 'Orient Kamasu diver RA-AA automatic sapphire japan', name: 'オリエント カマス' },
  { q: 'Orient Mako USA II III diver automatic japan', name: 'オリエント マコ' },
  { q: 'Orient Ray II diver automatic 200m japan', name: 'オリエント レイ' },
  { q: 'Curel face wash japan', name: 'キュレル洗顔フォーム' },
  { q: 'Curel moisture cream japan', name: 'キュレルフェイスクリーム' },
  { q: 'Rohto Melano CC vitamin C serum japan', name: 'メラノCC美容液' },
  { q: 'Hada Labo Gokujyun premium lotion japan', name: '肌ラボ極潤プレミアム化粧水' },
  { q: 'Cezanne foundation japan', name: 'セザンヌファンデ' },
  { q: 'Cezanne eyebrow pencil japan', name: 'セザンヌ眉ペンシル' },
  { q: 'excel skinny rich shadow japan', name: 'エクセルスキニーリッチシャドウ' },
  { q: 'Canmake Perfect Stylist Eyes palette japan', name: 'キャンメイクパーフェクトスタイリストアイズ' },
  { q: 'Canmake cream cheek blush japan', name: 'キャンメイククリームチーク' },
  { q: 'Kate Lip Monster lipstick japan', name: 'KATEリップモンスター' },
  { q: 'Kate Designing Eyebrow 3D japan', name: 'KATEデザイニングアイブロウ3D' },
  { q: 'DHC Deep Cleansing Oil japan', name: 'DHCディープクレンジングオイル' },
  { q: 'DHC lip balm japan', name: 'DHC薬用リップクリーム' },
  { q: 'Senka Perfect Whip foam japan', name: '専科パーフェクトホイップ洗顔' },
  { q: 'Biore UV Aqua Rich watery essence japan', name: 'ビオレUVアクアリッチ日焼け止め' },
  { q: 'Heroine Make mascara waterproof japan', name: 'ヒロインメイクマスカラ' },
  { q: 'Kiss Me mascara remover japan', name: 'キスミーマスカラリムーバー' },
  { q: 'Lululun face mask sheet japan', name: 'ルルルンフェイスマスク' },
  { q: 'Shiseido eyelash curler japan', name: '資生堂アイラッシュカーラー' },
  { q: 'Cezanne cheek blush natural japan', name: 'セザンヌナチュラルチーク' },
  { q: 'Kanebo Kate eyeshadow palette japan', name: 'KATEアイシャドウパレット' },
  { q: 'Hada Labo Gokujyun cleansing foam japan', name: '肌ラボ極潤洗顔' },
  { q: 'Curel UV moisture milk japan', name: 'キュレルUVミルク' },
  { q: 'cinnamoroll plush japan', name: 'シナモロール ぬいぐるみ' },
  { q: 'kuromi plush japan', name: 'クロミ ぬいぐるみ' },
  { q: 'my melody plush japan', name: 'マイメロディ ぬいぐるみ' },
  { q: 'pompompurin plush japan', name: 'ポムポムプリン ぬいぐるみ' },
  { q: 'pochacco plush japan', name: 'ポチャッコ ぬいぐるみ' },
  { q: 'sanrio nuikatsu mini plush acrylic stand', name: 'サンリオ ぬいかつ アクスタセット' },
  { q: 'sumikko gurashi tenori plush san-x', name: 'すみっコ てのりぬいぐるみ' },
  { q: 'sumikko gurashi tokage plush', name: 'すみっコ とかげ ぬいぐるみ' },
  { q: 'sumikko gurashi shirokuma plush', name: 'すみっコ しろくま ぬいぐるみ' },
  { q: 'chokkori san plush japan', name: 'ちょっこりさん ぬいぐるみ' },
  { q: 'jujutsu kaisen plush gojo satoru japan', name: '呪術 五条 ぬいぐるみ' },
  { q: 'jujutsu kaisen acrylic stand japan', name: '呪術 アクリルスタンド' },
  { q: 'demon slayer plush nezuko japan', name: '鬼滅 禰豆子 ぬいぐるみ' },
  { q: 'demon slayer acrylic stand japan', name: '鬼滅 アクリルスタンド' },
  { q: 'spy family anya plush japan', name: 'SPY×FAMILY アーニャ ぬいぐるみ' },
  { q: 'spy family acrylic stand japan', name: 'SPY×FAMILY アクスタ' },
  { q: 'oshi no ko acrylic stand japan', name: '推しの子 アクリルスタンド' },
  { q: 'chainsaw man plush power makima japan', name: 'チェンソーマン ぬいぐるみ' },
  { q: 'haikyuu chopinui petit plush japan', name: 'ハイキュー ちょぴぬいぷち' },
  { q: 'sanrio can badge japan', name: 'サンリオ 缶バッジ' },
  { q: 'jujutsu kaisen can badge japan', name: '呪術 缶バッジ' },
  { q: 'chokonose premium figure japan banpresto', name: 'ちょこのせ プレミアムフィギュア' },
  { q: 'Pilot Custom 74 fountain pen 14k japan', name: 'パイロットカスタム74' },
  { q: 'Sailor 1911 fountain pen 21k japan', name: 'セーラー1911' },
  { q: 'Platinum 3776 Century fountain pen japan', name: 'プラチナ3776センチュリー' },
  { q: 'Pilot Vanishing Point Capless fountain pen japan', name: 'パイロットキャップレス' },
  { q: 'Pilot Iroshizuku ink bottle 50ml japan', name: '色彩雫インク' },
  { q: 'uni Kuru Toga mechanical pencil japan', name: 'クルトガ' },
  { q: 'Pentel EnerGel pen japan', name: 'ぺんてるエナージェル' },
  { q: 'uni Jetstream pen japan', name: '三菱ジェットストリーム' },
  { q: 'Sakura Pigma Micron pen set japan', name: 'ピグマミクロン' },
  { q: 'Tombow Mono eraser japan', name: 'トンボMONO消しゴム' },
  { q: 'Tojiro DP gyuto chef knife VG10 japan', name: '藤次郎DP牛刀' },
  { q: 'santoku knife VG10 damascus japan', name: '三徳ダマスカスVG10' },
  { q: 'nakiri knife japanese stainless japan', name: '菜切り包丁' },
  { q: 'Higonokami folding knife japan', name: '肥後守' },
  { q: 'Plarail train set Shinkansen takara tomy japan', name: 'プラレール新幹線' },
  { q: 'Hanayama cast puzzle japan', name: 'はなやまキャストパズル' },
  { q: 'Daiso whetstone sharpening stone japan', name: '砥石(日本)' },
  { q: 'Japanese folding fan sensu japan', name: '扇子' },
  { q: 'furoshiki wrapping cloth japanese japan', name: '風呂敷' },
  { q: 'guitar picks japan made tortex pick', name: 'ギターピック(日本)' },
  { q: 'shamisen koto picks plectrum japan', name: '和楽器爪/撥' },
];
