// eBay発掘キーワード（366本）。refresh.mjs(楽天マッチ) と ebaySoldWorker.mjs(Pixel落札発掘) で共有。
// {q: eBay検索語(英), name: 表示/ジャンルキー}。name は guessCategory/EXPECTED_GENRE と対応（refresh.mjs参照）。

// 【ユーザー厳命】関税問題/国際郵便で送れない航空危険物等は絶対にカタログ対象にしない。発掘(worker)と取込(refresh)の双方で除外＝SSOT。
//   明確な危険物ワードに限定（腕時計の「電池/ソーラー」やスプレーボトル等の正常品を巻き込まないよう bareの電池/スプレーは使わない）。
export const PROHIBITED_EXCLUDE = /香水|フレグランス|オードトワレ|オーデコロン|パフューム|perfume|cologne|fragrance|eau de|スプレー缶|エアゾール|エアゾル|ヘアスプレー|制汗スプレー|殺虫スプレー|aerosol|モバイルバッテリー|リチウムイオンバッテリー|power\s?bank|ライター|チャッカマン|\blighter\b|花火|火薬|爆竹|firework|カセットボンベ|ガスボンベ|gas\s?canister|マニキュア|除光液|ネイルリムーバー|nail\s?polish|消毒用アルコール|エタノール|医薬品|劇薬|農薬/i;

export const EBAY_JP_QUERIES = [
  // 【古着ヴィンテージ(2026-06-25追加)】中古カタログB(2nd STREET)向けのeBay落札相場(demand)をPixel発掘で集める。
  //   古着は新品sealedが無いのでvintage/used語で。category名は buildUsedCatalog2ndStreet.mjs の2nd ST日本語クエリと対応。
  { q: 'levis 501 vintage made in usa denim',          name: 'リーバイス501ヴィンテージ' },
  { q: 'levis vintage trucker jacket type 3 denim',    name: 'リーバイストラッカー' },
  { q: 'champion reverse weave vintage sweatshirt 80s', name: 'チャンピオンリバースウィーブ' },
  { q: 'carhartt vintage detroit jacket used',         name: 'カーハートヴィンテージ' },
  { q: 'patagonia retro x fleece vintage',             name: 'パタゴニアフリース' },
  { q: 'nike vintage nylon jacket windbreaker 90s',    name: 'ナイキヴィンテージ' },
  { q: 'stussy vintage 90s t-shirt used',              name: 'ステューシーヴィンテージ' },
  { q: 'harley davidson vintage t-shirt 90s usa',      name: 'ハーレーヴィンテージT' },
  { q: 'the north face vintage nuptse jacket 90s',     name: 'ノースフェイスヴィンテージ' },
  { q: 'comme des garcons used jacket',                name: 'コムデギャルソン' },
  { q: 'yohji yamamoto used jacket',                   name: 'ヨウジヤマモト' },
  { q: 'polo ralph lauren vintage 90s used',           name: 'ラルフローレンヴィンテージ' },

  // 【CASIO時計 拡充(2026-06-26・①)】型番がeBayタイトルに出る＝同一型番照合が効く＝中古カタログ(時計)の本命供給。
  { q: 'casio gshock GMW-B5000 full metal',  name: 'GショックフルメタルB5000' },
  { q: 'casio gshock GM-2100 metal bezel',   name: 'GショックメタルベゼルGM2100' },
  { q: 'casio gshock GM-5600 metal',         name: 'GショックメタルGM5600' },
  { q: 'casio gshock GA-2100 carbon core',   name: 'GショックカシオークGA2100' },
  { q: 'casio gshock GG-B100 mudmaster',     name: 'GショックマッドマスターGGB100' },
  { q: 'casio gshock GW-9400 rangeman',      name: 'GショックレンジマンGW9400' },
  { q: 'casio gshock GWF-A1000 frogman',     name: 'GショックフロッグマンGWFA1000' },
  { q: 'casio gshock GST-B400 g-steel',      name: 'GショックGスチールGSTB400' },
  { q: 'casio gshock DW-5600 origin',        name: 'GショックDW5600オリジン' },
  { q: 'casio gshock GA-110 series',         name: 'GショックGA110' },
  { q: 'casio oceanus OCW-T200 titanium',    name: 'オシアナスOCWT200' },
  { q: 'casio oceanus OCW-S5000 manta',      name: 'オシアナスマンタOCWS5000' },
  { q: 'casio protrek PRW-6900 triple sensor', name: 'プロトレックPRW6900' },
  { q: 'casio edifice EQB-1000 bluetooth',   name: 'エディフィスEQB1000' },
  { q: 'casio edifice EQB-800',              name: 'エディフィスEQB800' },
  { q: 'casio vintage A168 silver',          name: 'カシオヴィンテージA168' },
  { q: 'casio vintage F-91W',                name: 'カシオF91W' },
  { q: 'casio royale AE-1200 world time',    name: 'カシオロイヤルAE1200' },

  { q: 'pokemon card booster box japanese sealed',  name: 'ポケモンカード' },
  { q: 'yu-gi-oh card booster box japanese sealed',  name: '遊戯王' },
  { q: 'one piece card game booster box japanese',   name: 'ワンピースカード' },
  { q: 'gunpla model kit bandai master grade',       name: 'ガンプラMG' },
  { q: 'gunpla high grade bandai japan new',         name: 'ガンプラHG' },
  { q: 'nendoroid figure good smile new sealed',     name: 'ねんどろいど' },
  { q: 'lego set japan new sealed',                  name: 'LEGO' },
  { q: 'seiko watch new japan',                      name: 'セイコー' },
  { q: 'casio g-shock new japan',                    name: 'Gショック' },
  { q: 'shiseido skincare japan new',                name: '資生堂' },
  { q: 'tomica diecast car japan new',               name: 'トミカ' },
  { q: 'amiibo nintendo new japan sealed',           name: 'アミーボ' },
  { q: 'dragon ball fusion world booster box japanese sealed',                 name: 'DBフュージョンワールド' },
  { q: 'weiss schwarz hololive booster box japanese sealed',                   name: 'ヴァイス ホロライブ' },
  { q: 'digimon card game booster box japanese sealed bandai',                 name: 'デジモンカード' },
  { q: 'amiibo card animal crossing japanese sealed booster',                  name: 'どうぶつの森amiiboカード' },
  { q: 'gundam RG real grade model kit bandai japan new sealed',               name: 'ガンプラRG' },
  { q: 'gundam PG perfect grade unleashed model kit bandai japan new sealed',  name: 'ガンプラPG' },
  { q: 'gundam entry grade EG model kit bandai japan new sealed',              name: 'ガンプラEG' },
  { q: '30MM armored core VI model kit bandai japan new sealed',               name: '30MM ACVI' },
  { q: 's.h.figuarts dragon ball figure japan new sealed',                     name: 'SHFドラゴンボール' },
  { q: 's.h.figuarts demon slayer figure new japan',                          name: 'SHF鬼滅' },
  { q: 'figma figure max factory japan new sealed',                           name: 'figma' },
  { q: 'pop up parade figure good smile new japan',                           name: 'POP UP PARADE' },
  { q: 'metal build gundam bandai figure japan new sealed',                    name: 'METAL BUILD' },
  { q: 'kotobukiya megami device frame arms girl model kit japan new sealed',  name: 'メガミ/FAガール' },
  { q: 'casio oceanus watch japan new',                                       name: 'オシアナス' },
  { q: 'citizen attesa eco-drive radio watch japan new',                       name: 'アテッサ' },
  { q: 'orient bambino automatic watch japan new',                            name: 'オリエント バンビーノ' },
  { q: 'anessa perfect uv sunscreen spf50 japan new',                         name: 'アネッサ' },
  { q: 'hada labo gokujyun lotion japan new sealed',                          name: 'ハダラボ極潤' },
  { q: 'canmake makeup japan new sealed',                                     name: 'キャンメイク' },
  { q: 'sk-ii facial treatment essence japan new sealed',                      name: 'SK-II' },
  { q: 'beyblade x takara tomy booster japan new sealed',                      name: 'ベイブレードX' },
  { q: 'tamiya mini 4wd model kit japan new sealed',                          name: 'ミニ四駆' },
  { q: 'pokemon center plush japan exclusive new with tag',                    name: 'ポケセンぬいぐるみ' },
  { q: 'pokemon card 151 booster box japanese sealed sv2a',                      name: 'ポケカ151' },
  { q: 'pokemon card elite trainer box japanese sealed',                        name: 'ポケカETB' },
  { q: 'pokemon card high class pack shiny treasure japanese sealed box',        name: 'ポケカハイクラス' },
  { q: 'yu-gi-oh structure deck japanese sealed konami',                        name: '遊戯王ストラク' },
  { q: 'one piece card game starter deck japanese sealed bandai',                name: 'ワンピーススタートデッキ' },
  { q: 'union arena booster box japanese sealed bandai',                         name: 'ユニオンアリーナ' },
  { q: 's.h.figuarts dragon ball son goku super saiyan figure japan new sealed', name: 'SHF悟空' },
  { q: 's.h.figuarts one piece monkey d luffy figure japan new sealed',          name: 'SHFルフィ' },
  { q: 's.h.figuarts naruto uzumaki figure japan new sealed',                    name: 'SHFナルト' },
  { q: 's.h.figuarts kamen rider figure japan new sealed',                       name: 'SHF仮面ライダー' },
  { q: 'nendoroid hatsune miku figure good smile japan new sealed',              name: 'ねんどミク' },
  { q: 'good smile company 1/7 scale figure anime japan new sealed',             name: 'GSC1/7スケール' },
  { q: 'casio g-shock GA-2100 carbon core guard japan new',                      name: 'GショックGA2100' },
  { q: 'casio g-shock DW-5600 japan new',                                        name: 'GショックDW5600' },
  { q: 'seiko 5 sports SRPD automatic watch japan new',                          name: 'セイコー5SRPD' },
  { q: 'seiko prospex turtle SRPE diver automatic watch japan new',              name: 'セイコープロスペックスSRPE' },
  { q: 'splatoon 3 nintendo switch japanese version new sealed',                 name: 'スプラ3SW' },
  { q: 'xenoblade chronicles 3 nintendo switch japanese version new sealed',     name: 'ゼノブレ3SW' },
  { q: 'chiikawa plush japan new with tag',                                      name: 'ちいかわぬいぐるみ' },
  { q: 'transformers takara tomy masterpiece figure japan new sealed',           name: 'TFマスターピース' },
  { q: 'soul of chogokin bandai diecast figure japan new sealed',                name: '超合金魂' },
  { q: 'seiko presage automatic watch japan new',                                name: 'セイコープレザージュ' },
  { q: 'seiko prospex samurai diver automatic watch japan new',                  name: 'プロスペックスサムライ' },
  { q: 'seiko prospex alpinist automatic watch japan new',                       name: 'プロスペックスアルピニスト' },
  { q: 'seiko prospex speedtimer chronograph watch japan new',                   name: 'プロスペックススピードタイマー' },
  { q: 'seiko 5 sports GMT automatic watch japan new',                           name: 'セイコー5GMT' },
  { q: 'seiko selection solar watch japan new',                                  name: 'セイコーセレクション' },
  { q: 'casio edifice chronograph watch japan new',                              name: 'カシオエディフィス' },
  { q: 'casio pro trek solar watch japan new',                                   name: 'カシオプロトレック' },
  { q: 'casio g-shock GW-M5610 tough solar watch japan new',                     name: 'GショックGWM5610' },
  { q: 'casio g-shock mudmaster watch japan new',                                name: 'Gショックマッドマスター' },
  { q: 'citizen promaster eco-drive diver watch japan new',                      name: 'シチズンプロマスター' },
  { q: 'citizen tsuyosa automatic watch japan new',                             name: 'シチズンTSUYOSA' },
  { q: 'citizen series 8 automatic watch japan new',                            name: 'シチズンシリーズ8' },
  { q: 'orient star automatic watch japan new',                                 name: 'オリエントスター' },
  { q: 'orient kamasu diver automatic watch japan new',                         name: 'オリエントカマス' },
  { q: 'orient mako diver automatic watch japan new',                           name: 'オリエントマコ' },
  { q: 'magic the gathering japanese booster box sealed',                     name: 'MTG日本語' },
  { q: 'cardfight vanguard booster box japanese sealed',                      name: 'ヴァンガード' },
  { q: 'duel masters booster box japanese sealed',                            name: 'デュエマ' },
  { q: 'battle spirits booster box japanese sealed bandai',                   name: 'バトスピ' },
  { q: 'shadowverse evolve booster box japanese sealed',                      name: 'シャドバエボルヴ' },
  { q: 'pokemon card scarlet violet booster box japanese sealed',             name: 'ポケカSV' },
  { q: 'one piece card game OP booster box japanese sealed bandai',           name: 'ワンピOPブースター' },
  { q: 'yu-gi-oh quarter century bonanza booster box japanese sealed',        name: '遊戯王QC' },
  { q: 'robot spirits bandai gundam figure japan new sealed',                 name: 'ROBOT魂' },
  { q: 'mafex medicom toy figure japan new sealed',                           name: 'MAFEX' },
  { q: 'kotobukiya artfx j figure japan new sealed',                          name: 'ARTFX' },
  { q: 'figuarts zero figure bandai japan new sealed',                        name: 'フィギュアーツZERO' },
  { q: 'revoltech kaiyodo figure japan new sealed',                           name: 'リボルテック' },
  { q: 're-ment miniature figure japan new sealed',                          name: 'リーメント' },
  { q: 'nendoroid doll good smile figure japan new sealed',                   name: 'ねんどろいどどーる' },
  { q: 'soul of chogokin bandai diecast robot japan new sealed',              name: '超合金GX' },
  { q: 'legend of zelda tears of the kingdom switch japanese new sealed',      name: 'ゼルダTOTK' },
  { q: 'super mario bros wonder switch japanese new sealed',                   name: 'マリオワンダー' },
  { q: 'pokemon scarlet violet switch japanese new sealed',                    name: 'ポケモンSVソフト' },
  { q: 'super smash bros ultimate switch japanese new sealed',                 name: 'スマブラSP' },
  { q: 'mario kart 8 deluxe switch japanese new sealed',                       name: 'マリカ8DX' },
  { q: 'tamiya 1/24 sports car model kit japan new sealed',                   name: 'タミヤ車' },
  { q: 'tamiya 1/35 military tank model kit japan new sealed',                name: 'タミヤミリタリー' },
  { q: 'tamiya 1/12 motorcycle model kit japan new sealed',                   name: 'タミヤバイク' },
  { q: 'hasegawa 1/48 aircraft model kit japan new sealed',                   name: 'ハセガワ飛行機' },
  { q: 'hasegawa 1/350 ship model kit japan new sealed',                      name: 'ハセガワ船' },
  { q: 'aoshima 1/24 car model kit japan new sealed',                         name: 'アオシマ車' },
  { q: 'fujimi 1/24 car model kit japan new sealed',                          name: 'フジミ車' },
  { q: 'kato n gauge shinkansen model train japan new',                       name: 'KATO新幹線' },
  { q: 'tomix n gauge train set japan new',                                   name: 'TOMIX電車' },
  { q: 'kato n gauge locomotive japan new',                                   name: 'KATO機関車' },
  { q: 'tomix n gauge limited japan new sealed',                              name: 'TOMIX限定' },
  { q: 'kato ho gauge model train japan new',                                 name: 'KATO HO' },
  { q: 'tomica premium diecast car japan new sealed',                         name: 'トミカプレミアム' },
  { q: 'kyosho 1/18 diecast car model japan new',                             name: '京商ミニカー' },
  { q: 'ignition model 1/18 diecast car japan new',                          name: 'イグニッション' },
  { q: 'tomica limited vintage neo diecast japan new',                        name: 'トミカLV NEO' },
  { q: 'hot wheels japan exclusive diecast car new',                          name: 'ホットウィール日本' },
  { q: 'pilot custom 74 fountain pen japan new',                              name: 'パイロットカスタム74' },
  { q: 'pilot capless vanishing point fountain pen japan new',                name: 'パイロットキャップレス' },
  { q: 'sailor 1911 pro gear fountain pen japan new',                         name: 'セーラー万年筆' },
  { q: 'platinum 3776 century fountain pen japan new',                        name: 'プラチナ3776' },
  { q: 'pilot kakuno fountain pen japan new',                                 name: 'パイロットカクノ' },
  { q: 'sanrio plush japan new with tag',                                     name: 'サンリオぬいぐるみ' },
  { q: 'sumikko gurashi plush japan new with tag',                            name: 'すみっコぐらし' },
  { q: 'pokemon center plush japan new with tag',                             name: 'ポケモンぬいぐるみ2' },
  { q: 'studio ghibli totoro plush japan new with tag',                       name: 'ジブリぬいぐるみ' },
  { q: 'chiikawa goods mascot japan new',                                     name: 'ちいかわグッズ' },
  { q: 'refa carat beauty roller japan new',                                  name: 'ReFaカラット' },
  { q: 'refa s carat ray beauty roller japan new',                           name: 'ReFa' },

  // ── キーワード拡張(高回転×楽天×非危険物・8カテゴリ並列生成→重複/危険物除外して追記・2026-06-25)。
  { q: 'pokemon japanese terastal festival sv8a booster box sealed', name: 'ポケカ テラスタルフェス' },
  { q: 'pokemon japanese mega evolution booster box sealed new', name: 'ポケカ メガエボリューション' },
  { q: 'pokemon japanese mega brave mega symphonia booster box', name: 'ポケカ メガブレイブ/シンフォニア' },
  { q: 'pokemon japanese black bolt white flare booster box sealed', name: 'ポケカ ブラックボルト/ホワイトフレア' },
  { q: 'yugioh quarter century bonanza booster box japanese sealed', name: '遊戯王 QCバランザ' },
  { q: 'yugioh rarity collection quarter century edition japanese box', name: '遊戯王 レアリティコレクションQC' },
  { q: 'yugioh structure deck japanese new sealed', name: '遊戯王 ストラクチャーデッキ' },
  { q: 'one piece card op12 legacy of the master booster box japanese', name: 'ワンピOP12 マスターの背中' },
  { q: 'one piece card op13 carrying on his will booster box japanese', name: 'ワンピOP13 受け継がれる意志' },
  { q: 'one piece card premium booster japanese sealed new', name: 'ワンピ プレミアムブースター' },
  { q: 'cardfight vanguard divinez booster box japanese sealed', name: 'ヴァンガード ディヴァインズ' },
  { q: 'cardfight vanguard crimson moon dz-bt14 booster box japan', name: 'ヴァンガード 真紅の月BT14' },
  { q: 'shadowverse evolve booster box japanese sealed new', name: 'シャドバ エボルヴ' },
  { q: 'duel masters booster pack japanese sealed new', name: 'デュエマ ブースターパック' },
  { q: 'battle spirits booster pack japanese sealed new', name: 'バトスピ ブースターパック' },
  { q: 'build divide booster box japanese tcg sealed', name: 'ビルディバイド' },
  { q: 'gundam card game booster box japanese sealed new', name: 'ガンダムカードゲーム' },
  { q: 'zx zillions of enemy x booster pack japanese sealed', name: 'Z/X ゼクス' },
  { q: 'bushiroad sleeve collection hg japanese card sleeves new', name: 'ブシロード スリーブHG' },
  { q: 'pokemon center japan deck case card case new sealed', name: 'ポケセン デッキケース' },
  { q: 'pokemon japanese deck shield card sleeves 64 new sealed', name: 'ポケカ 公式デッキシールド' },
  { q: 'yugioh card case duelist card protector japanese new', name: '遊戯王 カードケース' },
  { q: 'japanese tcg storage box card deck holder pokemon new', name: '日本TCG収納ボックス' },
  { q: 'one piece card game official sleeve japanese new sealed', name: 'ワンピカード 公式スリーブ' },
  { q: 'ichiban kuji one piece figure japan', name: '一番くじワンピース' },
  { q: 'ichiban kuji dragon ball figure japan', name: '一番くじドラゴンボール' },
  { q: 'ichiban kuji demon slayer figure japan', name: '一番くじ鬼滅' },
  { q: 'ichiban kuji jujutsu kaisen figure japan', name: '一番くじ呪術廻戦' },
  { q: 'ichiban kuji chainsaw man figure japan', name: '一番くじチェンソーマン' },
  { q: 'banpresto grandista figure japan', name: 'グランディスタ' },
  { q: 'banpresto ichiban kuji last one prize figure', name: 'ラストワン賞フィギュア' },
  { q: 'sega prize figure spm japan', name: 'セガSPMフィギュア' },
  { q: 'taito prize figure coreful japan', name: 'タイトーコアフル' },
  { q: 'furyu noodle stopper figure japan', name: 'フリューぬーどるストッパー' },
  { q: 're-ment miniature japan new', name: 'リーメントぷちサンプル' },
  { q: 're-ment sanrio miniature japan', name: 'リーメントサンリオ' },
  { q: 're-ment pokemon miniature japan', name: 'リーメントポケモン' },
  { q: 'shokugan candy toy figure japan', name: '食玩フィギュア' },
  { q: 'bandai shodo figure japan', name: 'SHODO食玩' },
  { q: 'gashapon capsule toy japan', name: 'ガチャ/カプセルトイ' },
  { q: 'bandai gunpla gashapon mobile suit ensemble', name: '機動戦士アンサンブル' },
  { q: 'qposket disney princess figure japan', name: 'Qposketディズニー' },
  { q: 'qposket dragon ball figure japan', name: 'QposketドラゴンボールZ' },
  { q: 'nakayoshi tirol mascot capsule japan', name: 'ご当地ガチャマスコット' },
  { q: 'ichiban kuji spy family figure japan', name: '一番くじスパイファミリー' },
  { q: 'banpresto relax time figure japan', name: 'リラックスタイムフィギュア' },
  { q: 'megahouse lookup figure japan', name: 'ルックアップシリーズ' },
  { q: 'Tamiya 1/24 Skyline GT-R model kit japan', name: 'タミヤ1/24スカイラインGT-R' },
  { q: 'Tamiya 1/24 Toyota Supra model kit japan', name: 'タミヤ1/24スープラ' },
  { q: 'Tamiya 1/24 sports car series new sealed japan', name: 'タミヤ1/24スポーツカーシリーズ' },
  { q: 'Tamiya 1/35 military tank model kit japan', name: 'タミヤ1/35ミリタリーミニチュア' },
  { q: 'Tamiya 1/12 motorcycle model kit japan', name: 'タミヤ1/12バイク' },
  { q: 'Tamiya 1/700 waterline ship model kit japan', name: 'タミヤ1/700ウォーターライン艦船' },
  { q: 'Hasegawa 1/72 aircraft model kit japan new', name: 'ハセガワ1/72航空機' },
  { q: 'Hasegawa 1/48 fighter jet model kit japan', name: 'ハセガワ1/48ジェット戦闘機' },
  { q: 'Hasegawa egg plane model kit japan', name: 'ハセガワたまごひこーき' },
  { q: 'Fujimi 1/700 ship model kit japan', name: 'フジミ1/700艦船' },
  { q: 'Aoshima 1/24 tuned car model kit japan', name: 'アオシマ1/24ザ・チューンドカー' },
  { q: 'Aoshima Initial D model kit 1/24 japan', name: 'アオシマ頭文字D' },
  { q: 'Aoshima 1/32 truck model kit japan dekotora', name: 'アオシマ1/32トラック野郎/デコトラ' },
  { q: 'Bandai 30MS option body parts model kit', name: '30MSオプションボディパーツ' },
  { q: 'Robot Spirits gundam action figure japan new', name: 'ロボット魂ガンダム' },
  { q: 'Bandai HGUC Zaku gunpla model kit japan', name: 'HGUCザク' },
  { q: 'Bandai HGUC Sazabi Nu Gundam model kit', name: 'HGUCサザビー/νガンダム' },
  { q: 'Bandai HG Gundam Aerial witch from mercury kit', name: 'HGエアリアル' },
  { q: 'Bandai Full Mechanics gundam model kit japan', name: 'フルメカニクスガンダム' },
  { q: 'Wave 1/20 maschinen krieger model kit japan', name: 'ウェーブ マシーネンクリーガー' },
  { q: 'Hasegawa creator works VF Macron model kit', name: 'ハセガワ マクロスVF' },
  { q: 'Kotobukiya Frame Arms model kit japan new', name: 'コトブキヤ フレームアームズ' },
  { q: 'Tamiya 1/24 Mazda RX-7 model kit japan', name: 'タミヤ1/24RX-7' },
  { q: 'Pokemon Legends Z-A Switch 2 japanese version new sealed', name: 'ポケモンZ-A日本版' },
  { q: 'Pokemon Scarlet Violet switch japanese version sealed', name: 'ポケモンSV日本版' },
  { q: 'Pokemon Pokopia switch 2 japanese new sealed', name: 'ポケピア日本版' },
  { q: 'Dragon Quest VII Reimagined switch 2 japanese sealed', name: 'DQ7リメイク日本版' },
  { q: 'Final Fantasy VII switch 2 japanese version sealed', name: 'FF7Switch日本版' },
  { q: 'Monster Hunter Stories 3 switch japanese sealed', name: 'MHストーリーズ3日本版' },
  { q: 'Famicom Detective Club switch japanese new sealed', name: 'ファミ探日本版' },
  { q: 'Super Mario Party Jamboree switch japanese sealed', name: 'マリパJ日本版' },
  { q: 'Kirby Air Riders switch 2 japanese version sealed', name: 'カービィエアライダー日本版' },
  { q: 'Mario Kart World switch 2 japanese version sealed', name: 'マリカワールド日本版' },
  { q: 'Donkey Kong Bananza switch 2 japanese sealed', name: 'DKバナンザ日本版' },
  { q: 'Atelier Yumia switch japanese version sealed', name: 'アトリエ日本版' },
  { q: 'Romancing SaGa switch japanese version new sealed', name: 'ロマサガ日本版' },
  { q: 'Hori split pad pro nintendo switch japanese new', name: 'Horiスプリットパッド' },
  { q: 'Hori split pad compact nintendo switch japanese new', name: 'Horiスプリットパッドコンパクト' },
  { q: 'Nintendo switch 2 pro controller japanese version new', name: 'Switch2プロコン日本版' },
  { q: 'Hori grip controller nintendo switch wired japanese new', name: 'Hori有線グリコン' },
  { q: 'Nintendo switch 2 carrying case japanese official new', name: 'Switch2純正ケース' },
  { q: 'Hori screen protector filter nintendo switch 2 japanese', name: 'Hori液晶保護フィルム' },
  { q: 'Nintendo switch 2 joy-con strap colored japanese new', name: 'ジョイコンストラップ日本版' },
  { q: 'Famicom mini classic console nintendo japanese new', name: 'ミニファミコン' },
  { q: 'Hori pokemon nintendo switch case pouch japanese new', name: 'Horiポケモンポーチ' },
  { q: 'Nintendo switch 2 dock set japanese official new', name: 'Switch2ドックセット日本版' },
  { q: 'Game Boy classic mini reissue nintendo japanese new', name: '復刻ゲームボーイ周辺' },
  { q: 'Seiko 5 Sports SSK GMT automatic japan', name: 'セイコー5GMT SSK' },
  { q: 'Seiko 5 Sports SRPK automatic japan new', name: 'セイコー5スポーツSRPK' },
  { q: 'Seiko Presage cocktail time automatic japan', name: 'プレザージュ カクテルタイム' },
  { q: 'Seiko Prospex Speedtimer solar chronograph SSC japan', name: 'プロスペックス スピードタイマー' },
  { q: 'Seiko Alpinist SPB121 green automatic japan', name: 'セイコー アルピニスト SPB121' },
  { q: 'Seiko Prospex Sumo SPB diver automatic japan', name: 'プロスペックス スモウ' },
  { q: 'Seiko Prospex Tuna solar diver japan', name: 'プロスペックス ツナ缶' },
  { q: 'Casio G-Shock GM-B2100 full metal japan', name: 'Gショック フルメタルB2100' },
  { q: 'Casio G-Shock MTG-B3000 MT-G metal japan', name: 'Gショック MT-G B3000' },
  { q: 'Casio G-Shock GM-2100 metal bezel japan', name: 'Gショック メタルベゼルGM2100' },
  { q: 'Casio G-Shock GA-B2100 tough solar bluetooth japan', name: 'Gショック GA-B2100ソーラー' },
  { q: 'Casio vintage A168WG gold digital japan', name: 'カシオ ヴィンテージ金A168' },
  { q: 'Casio vintage A158WA silver digital japan', name: 'カシオ ヴィンテージ銀A158' },
  { q: 'Casio Pro Trek PRG-340 solar triple sensor japan', name: 'プロトレック PRG-340' },
  { q: 'Casio Pro Trek PRW-3500 solar atomic japan', name: 'プロトレック PRW-3500' },
  { q: 'Casio Edifice EQB chronograph solar bluetooth japan', name: 'エディフィス EQBソーラー' },
  { q: 'Citizen Promaster diver BN0150 eco-drive japan', name: 'シチズン プロマスターBN0150' },
  { q: 'Citizen Tsuyosa NJ0150 automatic japan', name: 'シチズン ツヨサ NJ0150' },
  { q: 'Citizen Promaster Sky JY8078 pilot eco-drive japan', name: 'プロマスタースカイ JY8078' },
  { q: 'Orient Kamasu diver RA-AA automatic sapphire japan', name: 'オリエント カマス' },
  { q: 'Orient Mako USA II III diver automatic japan', name: 'オリエント マコ' },
  { q: 'Orient Ray II diver automatic 200m japan', name: 'オリエント レイ' },
  { q: 'Curel face wash japan', name: 'キュレル洗顔フォーム' },
  { q: 'Curel moisture cream japan', name: 'キュレルフェイスクリーム' },
  { q: 'Rohto Melano CC vitamin C serum japan', name: 'メラノCC美容液' },
  { q: 'Hada Labo Gokujyun premium lotion japan', name: '肌ラボ極潤プレミアム化粧水' },
  { q: 'Cezanne foundation japan', name: 'セザンヌファンデ' },
  { q: 'Cezanne eyebrow pencil japan', name: 'セザンヌ眉ペンシル' },
  { q: 'excel skinny rich shadow japan', name: 'エクセルスキニーリッチシャドウ' },
  { q: 'Canmake Perfect Stylist Eyes palette japan', name: 'キャンメイクパーフェクトスタイリストアイズ' },
  { q: 'Canmake cream cheek blush japan', name: 'キャンメイククリームチーク' },
  { q: 'Kate Lip Monster lipstick japan', name: 'KATEリップモンスター' },
  { q: 'Kate Designing Eyebrow 3D japan', name: 'KATEデザイニングアイブロウ3D' },
  { q: 'DHC Deep Cleansing Oil japan', name: 'DHCディープクレンジングオイル' },
  { q: 'DHC lip balm japan', name: 'DHC薬用リップクリーム' },
  { q: 'Senka Perfect Whip foam japan', name: '専科パーフェクトホイップ洗顔' },
  { q: 'Biore UV Aqua Rich watery essence japan', name: 'ビオレUVアクアリッチ日焼け止め' },
  { q: 'Heroine Make mascara waterproof japan', name: 'ヒロインメイクマスカラ' },
  { q: 'Kiss Me mascara remover japan', name: 'キスミーマスカラリムーバー' },
  { q: 'Lululun face mask sheet japan', name: 'ルルルンフェイスマスク' },
  { q: 'Shiseido eyelash curler japan', name: '資生堂アイラッシュカーラー' },
  { q: 'Cezanne cheek blush natural japan', name: 'セザンヌナチュラルチーク' },
  { q: 'Kanebo Kate eyeshadow palette japan', name: 'KATEアイシャドウパレット' },
  { q: 'Hada Labo Gokujyun cleansing foam japan', name: '肌ラボ極潤洗顔' },
  { q: 'Curel UV moisture milk japan', name: 'キュレルUVミルク' },
  { q: 'cinnamoroll plush japan', name: 'シナモロール ぬいぐるみ' },
  { q: 'kuromi plush japan', name: 'クロミ ぬいぐるみ' },
  { q: 'my melody plush japan', name: 'マイメロディ ぬいぐるみ' },
  { q: 'pompompurin plush japan', name: 'ポムポムプリン ぬいぐるみ' },
  { q: 'pochacco plush japan', name: 'ポチャッコ ぬいぐるみ' },
  { q: 'sanrio nuikatsu mini plush acrylic stand', name: 'サンリオ ぬいかつ アクスタセット' },
  { q: 'sumikko gurashi tenori plush san-x', name: 'すみっコ てのりぬいぐるみ' },
  { q: 'sumikko gurashi tokage plush', name: 'すみっコ とかげ ぬいぐるみ' },
  { q: 'sumikko gurashi shirokuma plush', name: 'すみっコ しろくま ぬいぐるみ' },
  { q: 'chokkori san plush japan', name: 'ちょっこりさん ぬいぐるみ' },
  { q: 'jujutsu kaisen plush gojo satoru japan', name: '呪術 五条 ぬいぐるみ' },
  { q: 'jujutsu kaisen acrylic stand japan', name: '呪術 アクリルスタンド' },
  { q: 'demon slayer plush nezuko japan', name: '鬼滅 禰豆子 ぬいぐるみ' },
  { q: 'demon slayer acrylic stand japan', name: '鬼滅 アクリルスタンド' },
  { q: 'spy family anya plush japan', name: 'SPY×FAMILY アーニャ ぬいぐるみ' },
  { q: 'spy family acrylic stand japan', name: 'SPY×FAMILY アクスタ' },
  { q: 'oshi no ko acrylic stand japan', name: '推しの子 アクリルスタンド' },
  { q: 'chainsaw man plush power makima japan', name: 'チェンソーマン ぬいぐるみ' },
  { q: 'haikyuu chopinui petit plush japan', name: 'ハイキュー ちょぴぬいぷち' },
  { q: 'sanrio can badge japan', name: 'サンリオ 缶バッジ' },
  { q: 'jujutsu kaisen can badge japan', name: '呪術 缶バッジ' },
  { q: 'chokonose premium figure japan banpresto', name: 'ちょこのせ プレミアムフィギュア' },
  { q: 'Pilot Custom 74 fountain pen 14k japan', name: 'パイロットカスタム74' },
  { q: 'Sailor 1911 fountain pen 21k japan', name: 'セーラー1911' },
  { q: 'Platinum 3776 Century fountain pen japan', name: 'プラチナ3776センチュリー' },
  { q: 'Pilot Vanishing Point Capless fountain pen japan', name: 'パイロットキャップレス' },
  { q: 'Pilot Iroshizuku ink bottle 50ml japan', name: '色彩雫インク' },
  { q: 'uni Kuru Toga mechanical pencil japan', name: 'クルトガ' },
  { q: 'Pentel EnerGel pen japan', name: 'ぺんてるエナージェル' },
  { q: 'uni Jetstream pen japan', name: '三菱ジェットストリーム' },
  { q: 'Sakura Pigma Micron pen set japan', name: 'ピグマミクロン' },
  { q: 'Tombow Mono eraser japan', name: 'トンボMONO消しゴム' },
  { q: 'Tojiro DP gyuto chef knife VG10 japan', name: '藤次郎DP牛刀' },
  { q: 'santoku knife VG10 damascus japan', name: '三徳ダマスカスVG10' },
  { q: 'nakiri knife japanese stainless japan', name: '菜切り包丁' },
  { q: 'Higonokami folding knife japan', name: '肥後守' },
  { q: 'Plarail train set Shinkansen takara tomy japan', name: 'プラレール新幹線' },
  { q: 'Hanayama cast puzzle japan', name: 'はなやまキャストパズル' },
  { q: 'Daiso whetstone sharpening stone japan', name: '砥石(日本)' },
  { q: 'Japanese folding fan sensu japan', name: '扇子' },
  { q: 'furoshiki wrapping cloth japanese japan', name: '風呂敷' },
  { q: 'guitar picks japan made tortex pick', name: 'ギターピック(日本)' },
  { q: 'shamisen koto picks plectrum japan', name: '和楽器爪/撥' },

  // ── ジャンル拡張②(カメラ周辺/釣具/レコード針/ブラインドボックス/ホビー工具/プラモ/文具/楽器小物・2026-06-25)。
  //    5クラスタ並列リサーチ→「楽天で新品潤沢×中〜低単価×軽量×非危険物×現金黒字」で採点し採用。
  //    ⚠️見送り(deferred)=中古フィルムカメラ/オールドレンズ(要古物商)・カメラ本体/mini Linkプリンタ(リチウム内蔵)・
  //      最上位リール/高級時計(現金薄利)・ガス器具/燃料(IATA危険物)・BOSS等ACペダル(100V電圧問題)・アナログ盤(重/割れ)。
  // カメラ周辺(既存に1本も無かった空白を最優先で埋める)
  { q: 'fujifilm instax mini film twin pack japan new sealed',        name: 'instaxミニフィルム' },
  { q: 'fujifilm instax mini film value pack 60 sheets japan new',     name: 'instaxミニフィルムバリューパック' },
  { q: 'fujifilm instax wide film twin pack japan new sealed',         name: 'instaxワイドフィルム' },
  { q: 'fujifilm instax square film twin pack japan new sealed',       name: 'instaxスクエアフィルム' },
  { q: 'fujifilm instax mini rainbow design film japan new sealed',    name: 'instaxデザインフィルム' },
  { q: 'K&F Concept mount adapter leica m to sony e japan new',        name: 'マウントアダプターLM→SE' },
  { q: 'K&F Concept lens mount adapter m42 to sony e japan new',       name: 'マウントアダプターM42→SE' },
  { q: 'K&F Concept mount adapter nikon f to fujifilm x japan new',    name: 'マウントアダプターNF→FX' },
  { q: 'K&F Concept lens mount adapter canon ef to sony e japan new',  name: 'マウントアダプターEF→SE' },
  { q: 'kenko PL polarizing filter japan new sealed',                 name: 'ケンコーPLフィルター' },
  { q: 'hoya ND filter japan new sealed',                             name: 'HOYA NDフィルター' },
  { q: 'marumi DHG protect lens filter japan new',                    name: 'マルミ プロテクトフィルター' },
  { q: 'kenko ZX C-PL circular polarizer japan new',                  name: 'ケンコーZX C-PL' },
  // 釣具(日本製が世界標準・消耗品で回転速い・軽量で関税$100未満)
  { q: 'shimano metal jig japan new',                                 name: 'シマノ メタルジグ' },
  { q: 'daiwa saltiga jig japan new',                                 name: 'ダイワ ソルティガ ジグ' },
  { q: 'major craft jigpara metal jig japan new',                     name: 'メジャークラフト ジグパラ' },
  { q: 'hayabusa jack eye slow jig japan new',                        name: 'ハヤブサ ジャックアイ' },
  { q: 'megabass lure japan new',                                     name: 'メガバス ルアー' },
  { q: 'jackall lure japan new',                                      name: 'ジャッカル ルアー' },
  { q: 'duo realis lure japan new',                                   name: 'DUO レアリス' },
  { q: 'evergreen lure japan new',                                    name: 'エバーグリーン ルアー' },
  { q: 'yamashita egi oh squid jig japan new',                        name: 'ヤマシタ エギ王' },
  { q: 'yo-zuri aurie-q egi squid jig japan new',                     name: 'ヨーヅリ アオリーQ' },
  { q: 'shimano sephia egi japan new',                               name: 'シマノ セフィア エギ' },
  { q: 'ygk pe braid line japan new',                                 name: 'YGK PEライン' },
  { q: 'varivas pe braid line japan new',                             name: 'バリバス PEライン' },
  { q: 'sunline pe braid line japan new',                            name: 'サンライン PEライン' },
  { q: 'gamakatsu hook japan new',                                    name: 'がまかつ フック' },
  { q: 'owner hook treble japan new',                                 name: 'オーナー トレブルフック' },
  { q: 'decoy snap swivel japan new',                                 name: 'DECOY スナップ/スイベル' },
  // オーディオ/レコード針(無電源・小型・消耗交換需要・米バイナル成長)
  { q: 'Audio-Technica VM540ML phono cartridge japan new',            name: 'オーディオテクニカ VM540ML カートリッジ' },
  { q: 'Audio-Technica AT-VM95E phono cartridge japan new',           name: 'オーディオテクニカ AT-VM95E カートリッジ' },
  { q: 'Audio-Technica AT-VM95ML phono cartridge japan new',          name: 'オーディオテクニカ AT-VM95ML カートリッジ' },
  { q: 'Nagaoka JN-P110 replacement stylus japan new',               name: 'ナガオカ JN-P110 交換針' },
  { q: 'Nagaoka JN-P200 stylus MP-200 japan new',                    name: 'ナガオカ JN-P200 交換針' },
  { q: 'JICO replacement stylus japan made new',                      name: 'JICO 交換針' },
  // ブラインドボックス(国際マークアップ大・新作継続・軽量低単価)
  { q: 'sonny angel mini figure blind box japan new sealed',          name: 'ソニーエンジェル' },
  { q: 'sonny angel hippers blind box japan new sealed',              name: 'ソニーエンジェルHIPPERS' },
  { q: 'smiski blind box japan new sealed',                           name: 'スミスキー' },
  { q: 'smiski secret series blind box japan new',                    name: 'スミスキー(シリーズ)' },
  // ホビー: ジグソーパズル/工具/プラモ(既存はガンプラ偏重→工具・他IPプラモの空白)
  { q: 'ensky jigsaw puzzle 1000 piece japanese anime new sealed',    name: 'エンスカイ1000ピースパズル' },
  { q: 'ensky art crystal jigsaw puzzle studio ghibli japan new sealed', name: 'アートクリスタルパズル ジブリ' },
  { q: 'beverly jigsaw puzzle japan new sealed 1000 piece',           name: 'ビバリー1000ピースパズル' },
  { q: 'godhand ultimate nipper 5.0 model kit japan new',             name: 'ゴッドハンド アルティメットニッパー' },
  { q: 'godhand nipper SPN-120 single blade japan new',               name: 'ゴッドハンド片刃ニッパー' },
  { q: 'tamiya sharp pointed side cutter model nipper japan new',     name: 'タミヤ薄刃ニッパー' },
  { q: 'gundam marker panel line pen set GM01 GM02 GM03 japan new',   name: 'ガンダムマーカー パネルライン' },
  { q: 'gundam marker EX pen mr hobby gunze japan new',               name: 'ガンダムマーカーEX' },
  { q: 'pokemon plamo collection select series bandai japan new sealed', name: 'ポケプラ セレクト' },
  { q: 'pokemon plamo collection quick bandai japan new sealed',      name: 'ポケプラ クイック' },
  { q: 'plamax max factory model kit japan new sealed',               name: 'PLAMAXプラモ' },
  { q: 'bandai super mini pla model kit japan new sealed',            name: 'スーパーミニプラ' },
  // 文具(海外カルト人気・軽量で現金率高い)
  { q: 'hobonichi techo planner 2026 japan new',                     name: 'ほぼ日手帳' },
  { q: 'travelers notebook midori leather refill japan new',          name: 'トラベラーズノート' },
  { q: 'mt washi tape masking tape japan new',                       name: 'mtマスキングテープ' },
  { q: 'zebra mildliner highlighter set japan new',                  name: 'ゼブラ マイルドライナー' },
  // 楽器小物(無電源 or 電池抜き発送・電圧問題なしの物だけ)
  { q: 'Korg Pitchclip 2 plus clip-on tuner japan new',              name: 'コルグ Pitchclip 2+ クリップチューナー' },
  { q: 'Vox amPlug 2 AC30 headphone guitar amp japan new',           name: 'VOX amPlug 2 AC30 ヘッドホンアンプ' },
  { q: 'Yamaha Pianica P-37D melodica japan new',                    name: 'ヤマハ ピアニカ P-37D' },
  { q: 'Suzuki harmonica Manji M-20 japan new',                      name: '鈴木 ハーモニカ Manji M-20' },
  // アウトドア(チタン食器のみ・ガス器具/燃料は危険物で除外)
  { q: 'snow peak titanium mug japan new',                            name: 'スノーピーク チタンマグ' },

  // ── 【ハードオフ中古の本領＝型番で売れる中古(2026-06-26)】eBay落札相場(demand)を発掘→buildがハードオフ現在庫と
  //    同一型番で突合。新品sealed(TCG/フィギュア/ゲームソフト)はハードオフ中古×型番照合と相性が悪いので避け、
  //    「型番がeBayタイトルに出る×ハードオフが中古で扱う×輸出できる(非危険物)」ジャンルに限定。name は USED_GENRE_KW と対応＋ハードオフ検索語も兼ねる。
  // ポータブルオーディオ(軽量・eBay高需要・型番一致しやすい)
  { q: 'sony walkman cassette WM personal player japan',  name: 'ソニー ウォークマン' },
  { q: 'sony walkman MD minidisc player MZ japan',        name: 'ソニー MDウォークマン' },
  { q: 'sony walkman NW digital audio player japan',      name: 'ソニー ウォークマンNW' },
  { q: 'sony MDR headphones japan',                       name: 'ソニー MDR ヘッドホン' },
  { q: 'audio-technica ATH headphones japan',             name: 'オーディオテクニカ ATH ヘッドホン' },
  { q: 'apple ipod classic nano touch japan',             name: 'iPod 本体' },
  // オーディオ機器(ハードオフの看板・型番で売れる。重量/電圧はあるが高値)
  { q: 'technics SL turntable record player japan',       name: 'テクニクス ターンテーブル' },
  { q: 'pioneer stereo amplifier japan',                  name: 'パイオニア アンプ' },
  { q: 'marantz amplifier cd player japan',               name: 'マランツ アンプ' },
  { q: 'denon amplifier cd player japan',                 name: 'デノン アンプ' },
  { q: 'onkyo amplifier receiver japan',                  name: 'オンキヨー アンプ' },
  { q: 'sansui vintage amplifier japan',                  name: 'サンスイ アンプ' },
  { q: 'yamaha integrated amplifier japan',               name: 'ヤマハ アンプ' },
  // カメラ・レンズ(軽量・eBay高需要・型番がタイトルに出る。中古は古物商前提)
  { q: 'canon AE-1 A-1 film camera slr japan',            name: 'キヤノン フィルムカメラ' },
  { q: 'nikon FM FE film camera slr japan',               name: 'ニコン フィルムカメラ' },
  { q: 'olympus OM film camera slr japan',                name: 'オリンパス フィルムカメラ' },
  { q: 'pentax film camera slr japan',                    name: 'ペンタックス フィルムカメラ' },
  { q: 'canon EF lens japan',                             name: 'キヤノン レンズ' },
  { q: 'nikon nikkor lens japan',                         name: 'ニコン レンズ' },
  { q: 'sony alpha E mount lens japan',                   name: 'ソニー レンズ' },
  { q: 'sigma lens japan',                                name: 'シグマ レンズ' },
  { q: 'tamron lens japan',                               name: 'タムロン レンズ' },
  { q: 'minolta rokkor lens vintage japan',              name: 'ミノルタ レンズ' },
  // レトロゲーム機(ハードオフ強い・eBay高需要・名前/型番で出る)
  { q: 'nintendo 64 console japan',                       name: 'ニンテンドー64 本体' },
  { q: 'nintendo gamecube console japan',                 name: 'ゲームキューブ 本体' },
  { q: 'super famicom snes console japan',                name: 'スーパーファミコン 本体' },
  { q: 'nintendo game boy advance console japan',         name: 'ゲームボーイ 本体' },
  { q: 'sega saturn console japan',                       name: 'セガサターン 本体' },
  { q: 'sega dreamcast console japan',                    name: 'ドリームキャスト 本体' },
  { q: 'sega mega drive genesis console japan',           name: 'メガドライブ 本体' },
  { q: 'sony playstation 2 console japan',                name: 'プレイステーション2 本体' },
  { q: 'sony psp console japan',                          name: 'PSP 本体' },
  { q: 'sony ps vita console japan',                      name: 'PS Vita 本体' },
  // エフェクター/小型楽器(軽量・型番で売れる。9V電源は世界共通アダプタ)
  { q: 'boss guitar effects pedal japan',                 name: 'BOSS エフェクター' },
  { q: 'korg effects pedal tuner japan',                  name: 'KORG エフェクター' },
  { q: 'zoom multi effects processor japan',              name: 'ZOOM マルチエフェクター' },

  // ===== 【中古カタログ供給拡大 2026-06-28・①】時計以外へ大幅拡張（489件追加）。
  //   q=eBay英語検索(型番) / name=ハードオフ検索語兼カテゴリ(USED_GENRE_KW通過済み)。多エージェント生成→重複/危険物/対象外を除外。 =====
  // --- セイコー腕時計 (54) ---
  { q: 'Seiko Presage Cocktail Time SRPB41'             , name: 'セイコー プレザージュ 腕時計 SRPB41' },
  { q: 'Seiko Presage Cocktail Time SRPB43'             , name: 'セイコー プレザージュ 腕時計 SRPB43' },
  { q: 'Seiko Presage Cocktail Time Sunset SRPK53'      , name: 'セイコー プレザージュ 腕時計 SRPK53' },
  { q: 'Seiko Presage SARX055 Baby Tuna'                , name: 'セイコー プレザージュ 腕時計 SARX055' },
  { q: 'Seiko Presage Enamel SPB047'                    , name: 'セイコー プレザージュ 腕時計 SPB047' },
  { q: 'Seiko Presage Sharp Edged SPB167'               , name: 'セイコー プレザージュ 腕時計 SPB167' },
  { q: 'Seiko Presage SRPC01 Power Reserve'             , name: 'セイコー プレザージュ 腕時計 SRPC01' },
  { q: 'Seiko Presage SSA343 Open Heart'                , name: 'セイコー プレザージュ 腕時計 SSA343' },
  { q: 'Seiko Prospex Sumo SPB101'                      , name: 'セイコー プロスペックス スモウ 腕時計 SPB101' },
  { q: 'Seiko Prospex Sumo SBDC033'                     , name: 'セイコー プロスペックス スモウ 腕時計 SBDC033' },
  { q: 'Seiko Prospex Turtle SRP777'                    , name: 'セイコー プロスペックス タートル 腕時計 SRP777' },
  { q: 'Seiko Prospex Turtle SRPC23 PADI'               , name: 'セイコー プロスペックス タートル 腕時計 SRPC23' },
  { q: 'Seiko Prospex Samurai SRPB51'                   , name: 'セイコー プロスペックス サムライ 腕時計 SRPB51' },
  { q: 'Seiko Prospex Samurai SRPB09 Blue Lagoon'       , name: 'セイコー プロスペックス サムライ 腕時計 SRPB09' },
  { q: 'Seiko Prospex Monster SRP307'                   , name: 'セイコー プロスペックス モンスター 腕時計 SRP307' },
  { q: 'Seiko Prospex Tuna SBBN031'                     , name: 'セイコー プロスペックス ツナ 腕時計 SBBN031' },
  { q: 'Seiko Prospex Tuna SBBN033'                     , name: 'セイコー プロスペックス ツナ 腕時計 SBBN033' },
  { q: 'Seiko Prospex SPB143 62MAS'                     , name: 'セイコー プロスペックス 腕時計 SPB143' },
  { q: 'Seiko Prospex SPB153 62MAS'                     , name: 'セイコー プロスペックス 腕時計 SPB153' },
  { q: 'Seiko Prospex SPB051 Marinemaster'              , name: 'セイコー プロスペックス 腕時計 SPB051' },
  { q: 'Seiko Prospex Marinemaster SBDX017'             , name: 'セイコー マリーンマスター 腕時計 SBDX017' },
  { q: 'Seiko Prospex Alpinist SARB017'                 , name: 'セイコー アルピニスト 腕時計 SARB017' },
  { q: 'Seiko Prospex Alpinist SPB121'                  , name: 'セイコー プロスペックス アルピニスト 腕時計 SPB121' },
  { q: 'Seiko Prospex Alpinist SPB123'                  , name: 'セイコー プロスペックス アルピニスト 腕時計 SPB123' },
  { q: 'Seiko Astron GPS Solar SBXB037'                 , name: 'セイコー アストロン 腕時計 SBXB037' },
  { q: 'Seiko Astron GPS Solar SSH023'                  , name: 'セイコー アストロン 腕時計 SSH023' },
  { q: 'Seiko Astron SSH045 Titanium'                   , name: 'セイコー アストロン 腕時計 SSH045' },
  { q: 'Seiko King Seiko KSK SJE083'                    , name: 'キングセイコー 腕時計 SJE083' },
  { q: 'Seiko King Seiko SPB279'                        , name: 'キングセイコー 腕時計 SPB279' },
  { q: 'Seiko King Seiko SPB281'                        , name: 'キングセイコー 腕時計 SPB281' },
  { q: 'Seiko 5 Sports SRPG27 GMT'                      , name: 'セイコー5スポーツ 腕時計 SRPG27' },
  { q: 'Seiko 5 Sports SSK001 GMT'                      , name: 'セイコー5スポーツ 腕時計 SSK001' },
  { q: 'Seiko 5 Sports SSK003 GMT'                      , name: 'セイコー5スポーツ 腕時計 SSK003' },
  { q: 'Seiko 5 Sports Street SBSA063'                  , name: 'セイコー5スポーツ 腕時計 SBSA063' },
  { q: 'Seiko SKX007 Diver'                             , name: 'セイコー ダイバー 腕時計 SKX007' },
  { q: 'Seiko SKX009 Pepsi Diver'                       , name: 'セイコー ダイバー 腕時計 SKX009' },
  { q: 'Seiko SKX013 Diver'                             , name: 'セイコー ダイバー 腕時計 SKX013' },
  { q: 'Seiko SARB033'                                  , name: 'セイコー メカニカル 腕時計 SARB033' },
  { q: 'Seiko SARB035 Cream'                            , name: 'セイコー メカニカル 腕時計 SARB035' },
  { q: 'Seiko Sportura Kinetic SNL049'                  , name: 'セイコー スポーチュラ 腕時計 SNL049' },
  { q: 'Seiko Brightz SAGA series'                      , name: 'セイコー ブライツ 腕時計 SAGA' },
  { q: 'Seiko Spirit Smart SCVE series'                 , name: 'セイコー スピリット 腕時計 SCVE' },
  { q: 'Seiko Prospex LX SNR029'                        , name: 'セイコー プロスペックス LX 腕時計 SNR029' },
  { q: 'Seiko Prospex Speedtimer SSC813 Solar'          , name: 'セイコー プロスペックス スピードタイマー 腕時計 SSC813' },
  { q: 'Seiko Prospex Speedtimer SBDL085'               , name: 'セイコー プロスペックス スピードタイマー 腕時計 SBDL085' },
  { q: 'Seiko Prospex SRPE05 Save the Ocean Turtle'     , name: 'セイコー プロスペックス 腕時計 SRPE05' },
  { q: 'Seiko Prospex SRPD21 Save the Ocean Samurai'    , name: 'セイコー プロスペックス サムライ 腕時計 SRPD21' },
  { q: 'Seiko Presage SSA397 GMT'                       , name: 'セイコー プレザージュ 腕時計 SSA397' },
  { q: 'Seiko Prospex SPB207 Alpinist'                  , name: 'セイコー プロスペックス アルピニスト 腕時計 SPB207' },
  { q: 'Seiko Prospex SPB237 1959 Alpinist'             , name: 'セイコー プロスペックス アルピニスト 腕時計 SPB237' },
  { q: 'Seiko Recraft SNKP27'                           , name: 'セイコー リクラフト 腕時計 SNKP27' },
  { q: 'Seiko Prospex Baby Tuna SRP641'                 , name: 'セイコー プロスペックス ベビーツナ 腕時計 SRP641' },
  { q: 'Seiko Prospex SRPA21 PADI Turtle'               , name: 'セイコー プロスペックス タートル 腕時計 SRPA21' },
  { q: 'Seiko Prospex SBDC053 Sumo'                     , name: 'セイコー プロスペックス スモウ 腕時計 SBDC053' },
  // --- シチズン/カシオ/オリエント腕時計 (55) ---
  { q: 'Citizen Attesa Eco-Drive AT8040'                , name: 'シチズン アテッサ AT8040 腕時計' },
  { q: 'Citizen Attesa CB5044 Eco-Drive Radio'          , name: 'シチズン アテッサ CB5044 腕時計' },
  { q: 'Citizen Promaster Diver BN0150 Eco-Drive'       , name: 'シチズン プロマスター BN0150 腕時計' },
  { q: 'Citizen Promaster Aqualand BN2036 depth'        , name: 'シチズン プロマスター BN2036 腕時計' },
  { q: 'Citizen Promaster Sky BJ7000 Nighthawk'         , name: 'シチズン プロマスター ナイトホーク 腕時計' },
  { q: 'Citizen Series 8 NA1004 mechanical'             , name: 'シチズン シリーズ8 NA1004 腕時計' },
  { q: 'Citizen Series 8 870 NB6011 mechanical'         , name: 'シチズン シリーズ8 NB6011 腕時計' },
  { q: 'Citizen Tsuyosa NJ0150 automatic'               , name: 'シチズン ツヨサ NJ0150 腕時計' },
  { q: 'Citizen Tsuyosa NJ0151 automatic'               , name: 'シチズン ツヨサ NJ0151 腕時計' },
  { q: 'Citizen Eco-Drive Bullhead Chronograph AV0'     , name: 'シチズン ブルヘッド クロノグラフ 腕時計' },
  { q: 'Casio Edifice EQB-1100 Bluetooth solar'         , name: 'カシオ エディフィス EQB-1100 腕時計' },
  { q: 'Casio Edifice EFR-526 chronograph'              , name: 'カシオ エディフィス EFR-526 腕時計' },
  { q: 'Casio Edifice ECB-2000 solar Bluetooth'         , name: 'カシオ エディフィス ECB-2000 腕時計' },
  { q: 'Casio Oceanus OCW-T200 titanium radio'          , name: 'カシオ オシアナス OCW-T200 腕時計' },
  { q: 'Casio Oceanus Manta OCW-S100'                   , name: 'カシオ オシアナス マンタ 腕時計' },
  { q: 'Casio Protrek PRW-3500 triple sensor'           , name: 'カシオ プロトレック PRW-3500 腕時計' },
  { q: 'Casio Protrek PRW-6600 solar radio'             , name: 'カシオ プロトレック PRW-6600 腕時計' },
  { q: 'Casio Protrek PRG-600 solar'                    , name: 'カシオ プロトレック PRG-600 腕時計' },
  { q: 'Casio G-Shock Mudmaster GG-1000'                , name: 'カシオ Gショック マッドマスター GG-1000 腕時計' },
  { q: 'Casio G-Shock Frogman GWF-D1000'                , name: 'カシオ Gショック フロッグマン GWF-D1000 腕時計' },
  { q: 'Casio G-Shock Rangeman GW-9400'                 , name: 'カシオ Gショック レンジマン GW-9400 腕時計' },
  { q: 'Casio G-Shock MR-G titanium MRG'                , name: 'カシオ Gショック MR-G 腕時計' },
  { q: 'Casio G-Shock MT-G MTG-B2000'                   , name: 'カシオ Gショック MTG-B2000 腕時計' },
  { q: 'Casio G-Shock GravityMaster GWR-B1000'          , name: 'カシオ Gショック グラビティマスター 腕時計' },
  { q: 'Orient Bambino Version 2 FAC00 automatic'       , name: 'オリエント バンビーノ 腕時計' },
  { q: 'Orient Kamasu RA-AA0 diver automatic'           , name: 'オリエント カマス RA-AA0 腕時計' },
  { q: 'Orient Mako USA II diver automatic'             , name: 'オリエント マコ 腕時計' },
  { q: 'Orient Ray II diver automatic FAA02'            , name: 'オリエント レイ 腕時計' },
  { q: 'Orient Star RK automatic power reserve'         , name: 'オリエントスター 腕時計' },
  { q: 'Orient Sun and Moon automatic FAK00'            , name: 'オリエント サン&ムーン 腕時計' },
  { q: 'Hamilton Khaki Field Mechanical H69'            , name: 'ハミルトン カーキ フィールド 腕時計' },
  { q: 'Hamilton Khaki Field Auto H70 38mm'             , name: 'ハミルトン カーキ フィールド オート 腕時計' },
  { q: 'Hamilton Khaki Aviation H76 chronograph'        , name: 'ハミルトン カーキ アビエーション 腕時計' },
  { q: 'Hamilton Jazzmaster Open Heart H32'             , name: 'ハミルトン ジャズマスター 腕時計' },
  { q: 'Hamilton Ventura H24 electric'                  , name: 'ハミルトン ベンチュラ 腕時計' },
  { q: 'Hamilton Intra-Matic Auto Chrono H38'           , name: 'ハミルトン イントラマティック 腕時計' },
  { q: 'Tissot PRX Powermatic 80 automatic'             , name: 'ティソ PRX 腕時計' },
  { q: 'Tissot Seastar 1000 Powermatic 80 diver'        , name: 'ティソ シースター 腕時計' },
  { q: 'Tissot Gentleman Powermatic 80 silicium'        , name: 'ティソ ジェントルマン 腕時計' },
  { q: 'Seiko Presage Cocktail Time SRPB automatic'     , name: 'セイコー プレザージュ カクテル 腕時計' },
  { q: 'Seiko Prospex Turtle SRP777 diver'              , name: 'セイコー プロスペックス タートル 腕時計' },
  { q: 'Seiko Prospex Samurai SRPB diver'               , name: 'セイコー プロスペックス サムライ 腕時計' },
  { q: 'Seiko Prospex Sumo SPB diver automatic'         , name: 'セイコー プロスペックス スモウ 腕時計' },
  { q: 'Seiko Alpinist SARB017 automatic'               , name: 'セイコー アルピニスト 腕時計' },
  { q: 'Seiko Presage Sharp Edged SPB automatic'        , name: 'セイコー プレザージュ シャープエッジ 腕時計' },
  { q: 'Seiko Astron GPS Solar SBXC titanium'           , name: 'セイコー アストロン 腕時計' },
  { q: 'Citizen Eco-Drive Skyhawk JY8078 radio'         , name: 'シチズン スカイホーク 腕時計' },
  { q: 'Casio Lineage LCW-M100 solar radio titanium'    , name: 'カシオ リニエージ 腕時計' },
  { q: 'Orient Defender RA-AK automatic multi-eyes'     , name: 'オリエント ディフェンダー 腕時計' },
  { q: 'Hamilton Khaki Navy Scuba H82 diver'            , name: 'ハミルトン カーキ ネイビー スキューバ 腕時計' },
  { q: 'Tissot Le Locle Powermatic 80 automatic'        , name: 'ティソ ルロックル 腕時計' },
  { q: 'Citizen Promaster Tough BN0211 Eco-Drive'       , name: 'シチズン プロマスター タフ BN0211 腕時計' },
  { q: 'Casio Edifice Sospension EQB-2000 carbon'       , name: 'カシオ エディフィス EQB-2000 腕時計' },
  { q: 'Seiko 5 Sports SRPG GMT-style automatic'        , name: 'セイコー5スポーツ SRPG 腕時計' },
  { q: 'Citizen Bullhead Promaster Tsuno chrono'        , name: 'シチズン ツノ クロノ プロマスター 腕時計' },
  // --- カメラ・AFレンズ/ミラーレス (50) ---
  { q: 'Canon EF 50mm f/1.8 STM'                        , name: 'キヤノン EF 50mm F1.8 STM レンズ' },
  { q: 'Canon EF 50mm f/1.4 USM'                        , name: 'キヤノン EF 50mm F1.4 USM レンズ' },
  { q: 'Canon EF 85mm f/1.8 USM'                        , name: 'キヤノン EF 85mm F1.8 USM レンズ' },
  { q: 'Canon EF 24-70mm f/2.8L II USM'                 , name: 'キヤノン EF 24-70mm F2.8L レンズ' },
  { q: 'Canon EF 70-200mm f/4L USM'                     , name: 'キヤノン EF 70-200mm F4L レンズ' },
  { q: 'Canon RF 50mm f/1.8 STM'                        , name: 'キヤノン RF 50mm F1.8 STM レンズ' },
  { q: 'Canon EOS R8 body'                              , name: 'キヤノン EOS R8 ボディ' },
  { q: 'Canon EOS RP body'                              , name: 'キヤノン EOS RP ボディ' },
  { q: 'Canon EOS 6D Mark II body'                      , name: 'キヤノン EOS 6D Mark II ボディ' },
  { q: 'Canon EOS 90D body'                             , name: 'キヤノン EOS 90D ボディ' },
  { q: 'Nikon AF-S 50mm f/1.8G'                         , name: 'ニコン AF-S 50mm F1.8G レンズ' },
  { q: 'Nikon AF-S 35mm f/1.8G'                         , name: 'ニコン AF-S 35mm F1.8G レンズ' },
  { q: 'Nikon AF-S 85mm f/1.8G'                         , name: 'ニコン AF-S 85mm F1.8G レンズ' },
  { q: 'Nikon Z 50mm f/1.8 S'                           , name: 'ニコン Z 50mm F1.8 S レンズ' },
  { q: 'Nikon Z 24-70mm f/4 S'                          , name: 'ニコン Z 24-70mm F4 S レンズ' },
  { q: 'Nikon Z6 body'                                  , name: 'ニコン Z6 ボディ' },
  { q: 'Nikon Z5 body'                                  , name: 'ニコン Z5 ボディ' },
  { q: 'Nikon D750 body'                                , name: 'ニコン D750 ボディ' },
  { q: 'Nikon D7500 body'                               , name: 'ニコン D7500 ボディ' },
  { q: 'Sony FE 50mm f/1.8'                             , name: 'ソニー FE 50mm F1.8 レンズ' },
  { q: 'Sony FE 85mm f/1.8'                             , name: 'ソニー FE 85mm F1.8 レンズ' },
  { q: 'Sony FE 28-70mm f/3.5-5.6 OSS'                  , name: 'ソニー FE 28-70mm レンズ' },
  { q: 'Sony FE 24-105mm f/4 G OSS'                     , name: 'ソニー FE 24-105mm F4 G レンズ' },
  { q: 'Sony E 55-210mm f/4.5-6.3 OSS'                  , name: 'ソニー E 55-210mm レンズ' },
  { q: 'Sony Alpha a6400 body'                          , name: 'ソニー α6400 ボディ' },
  { q: 'Sony Alpha a7 III body'                         , name: 'ソニー α7III ボディ' },
  { q: 'Sony Alpha a7 II body'                          , name: 'ソニー α7II ボディ' },
  { q: 'Sony Alpha a6000 body'                          , name: 'ソニー α6000 ボディ' },
  { q: 'Fujifilm XF 35mm f/1.4 R'                       , name: 'フジフイルム XF 35mm F1.4 R レンズ' },
  { q: 'Fujifilm XF 18-55mm f/2.8-4 R LM OIS'           , name: 'フジ XF 18-55mm レンズ' },
  { q: 'Fujifilm XF 23mm f/2 R WR'                      , name: 'フジフイルム XF 23mm F2 レンズ' },
  { q: 'Fujifilm X-T30 body'                            , name: 'フジフイルム X-T30 ボディ' },
  { q: 'Fujifilm X-T3 body'                             , name: 'フジフイルム X-T3 ボディ' },
  { q: 'Fujifilm X100V body'                            , name: 'フジフイルム X100V カメラ' },
  { q: 'Sigma 30mm f/1.4 DC DN Sony E'                  , name: 'シグマ 30mm F1.4 DC DN レンズ' },
  { q: 'Sigma 16mm f/1.4 DC DN Sony E'                  , name: 'シグマ 16mm F1.4 DC DN レンズ' },
  { q: 'Sigma 35mm f/1.4 DG HSM Art'                    , name: 'シグマ 35mm F1.4 DG Art レンズ' },
  { q: 'Sigma 50mm f/1.4 DG HSM Art'                    , name: 'シグマ 50mm F1.4 DG Art レンズ' },
  { q: 'Tamron 28-75mm f/2.8 Di III RXD Sony'           , name: 'タムロン 28-75mm F2.8 レンズ' },
  { q: 'Tamron 17-28mm f/2.8 Di III RXD Sony'           , name: 'タムロン 17-28mm F2.8 レンズ' },
  { q: 'Tamron 70-300mm f/4.5-6.3 Di III RXD'           , name: 'タムロン 70-300mm レンズ' },
  { q: 'Olympus M.Zuiko 45mm f/1.8'                     , name: 'オリンパス M.ZUIKO 45mm F1.8 レンズ' },
  { q: 'Olympus M.Zuiko 12-40mm f/2.8 PRO'              , name: 'オリンパス 12-40mm F2.8 PRO レンズ' },
  { q: 'Panasonic Lumix 25mm f/1.7'                     , name: 'パナソニック LUMIX 25mm F1.7 レンズ' },
  { q: 'Panasonic Lumix G9 body'                        , name: 'パナソニック LUMIX G9 ボディ' },
  { q: 'Canon EF 100mm f/2.8L Macro IS USM'             , name: 'キヤノン EF 100mm F2.8L マクロ レンズ' },
  { q: 'Nikon AF-S 24-120mm f/4G ED VR'                 , name: 'ニコン AF-S 24-120mm F4 レンズ' },
  { q: 'Sony FE 70-200mm f/4 G OSS'                     , name: 'ソニー FE 70-200mm F4 G レンズ' },
  { q: 'Fujifilm XF 56mm f/1.2 R'                       , name: 'フジフイルム XF 56mm F1.2 R レンズ' },
  { q: 'Canon EOS M6 Mark II body'                      , name: 'キヤノン EOS M6 Mark II ボディ' },
  // --- フィルムカメラ・オールドレンズ (58) ---
  { q: 'Contax T2 35mm point and shoot'                 , name: 'Contax T2 コンパクトカメラ' },
  { q: 'Contax T3 titanium compact film camera'         , name: 'Contax T3 カメラ' },
  { q: 'Contax G2 rangefinder body'                     , name: 'Contax G2 ボディ カメラ' },
  { q: 'Contax RTS III 35mm SLR'                        , name: 'Contax RTS III カメラ' },
  { q: 'Contax Aria 35mm SLR body'                      , name: 'Contax Aria カメラ' },
  { q: 'Carl Zeiss Planar 50mm f1.4 C/Y'                , name: 'Carl Zeiss Planar 50mm レンズ' },
  { q: 'Carl Zeiss Planar 85mm f1.4 C/Y mount'          , name: 'Contax Planar 85mm レンズ' },
  { q: 'Carl Zeiss Distagon 28mm f2.8 Contax'           , name: 'Contax Distagon 28mm レンズ' },
  { q: 'Leica M6 35mm rangefinder body'                 , name: 'Leica M6 ボディ カメラ' },
  { q: 'Leica Summicron 50mm f2 lens'                   , name: 'Leica ズミクロン 50mm レンズ' },
  { q: 'Leica Elmar 50mm f3.5 collapsible'              , name: 'Leica エルマー 50mm レンズ' },
  { q: 'Leica CL film rangefinder body'                 , name: 'Leica CL カメラ' },
  { q: 'Leica Summicron 90mm f2 lens'                   , name: 'Leica ズミクロン 90mm レンズ' },
  { q: 'Leitz Minolta CL 40mm rangefinder'              , name: 'ミノルタ CL カメラ' },
  { q: 'Pentax 67 medium format body'                   , name: 'ペンタックス 67 カメラ' },
  { q: 'Pentax 6x7 105mm f2.4 lens'                     , name: 'ペンタックス 67 105mm レンズ' },
  { q: 'Pentax LX 35mm SLR body'                        , name: 'ペンタックス LX カメラ' },
  { q: 'Pentax MX 35mm SLR black'                       , name: 'ペンタックス MX カメラ' },
  { q: 'SMC Pentax-M 50mm f1.4 lens'                    , name: 'ペンタックス M 50mm レンズ' },
  { q: 'SMC Takumar 50mm f1.4 M42 lens'                 , name: 'スーパータクマー 50mm レンズ' },
  { q: 'Super Takumar 55mm f1.8 M42'                    , name: 'タクマー 55mm レンズ' },
  { q: 'Olympus OM-1 35mm SLR body'                     , name: 'オリンパス OM-1 カメラ' },
  { q: 'Olympus OM-2 SP 35mm SLR'                       , name: 'オリンパス OM-2 カメラ' },
  { q: 'Olympus OM-4 Ti titanium body'                  , name: 'オリンパス OM-4 カメラ' },
  { q: 'Zuiko 50mm f1.4 OM lens'                        , name: 'オリンパス ズイコー 50mm レンズ' },
  { q: 'Zuiko 50mm f1.8 OM lens'                        , name: 'ズイコー 50mm レンズ' },
  { q: 'Olympus 35 RC rangefinder film'                 , name: 'オリンパス 35RC カメラ' },
  { q: 'Olympus Pen F half frame body'                  , name: 'オリンパス PEN F カメラ' },
  { q: 'Minolta SRT 101 35mm SLR'                       , name: 'ミノルタ SRT カメラ' },
  { q: 'Minolta X-700 35mm SLR body'                    , name: 'ミノルタ X-700 カメラ' },
  { q: 'Minolta Rokkor 58mm f1.4 MC lens'               , name: 'ミノルタ ロッコール 58mm レンズ' },
  { q: 'Minolta MD Rokkor 50mm f1.4'                    , name: 'ミノルタ MD 50mm レンズ' },
  { q: 'Minolta CLE rangefinder body'                   , name: 'ミノルタ CLE カメラ' },
  { q: 'Canon AE-1 Program 35mm SLR'                    , name: 'キヤノン AE-1 カメラ' },
  { q: 'Canon A-1 35mm SLR body'                        , name: 'キヤノン A-1 カメラ' },
  { q: 'Canon FD 50mm f1.4 lens'                        , name: 'キヤノン FD 50mm レンズ' },
  { q: 'Canon F-1 35mm SLR body'                        , name: 'キヤノン F-1 カメラ' },
  { q: 'Canon Canonet QL17 GIII rangefinder'            , name: 'キヤノン キヤノネット カメラ' },
  { q: 'Nikon FM2 35mm SLR body'                        , name: 'ニコン FM2 カメラ' },
  { q: 'Nikon FE2 35mm SLR body'                        , name: 'ニコン FE2 カメラ' },
  { q: 'Nikon F3 HP 35mm SLR body'                      , name: 'ニコン F3 カメラ' },
  { q: 'Nikon F2 Photomic 35mm SLR'                     , name: 'ニコン F2 カメラ' },
  { q: 'Nikkor 50mm f1.4 Ai-S lens'                     , name: 'ニコン Ai-S 50mm レンズ' },
  { q: 'Nikkor 50mm f1.2 Ai-S lens'                     , name: 'ニコン Ai-S 50mm f1.2 レンズ' },
  { q: 'Nikkor 105mm f2.5 Ai lens'                      , name: 'ニコン 105mm レンズ' },
  { q: 'Nikon FM3A 35mm SLR body'                       , name: 'ニコン FM3A カメラ' },
  { q: 'Konica Hexar AF compact film camera'            , name: 'コニカ ヘキサー カメラ' },
  { q: 'Konica Hexanon 50mm f1.7 lens'                  , name: 'コニカ ヘキサノン 50mm レンズ' },
  { q: 'Konica Auto S2 rangefinder film'                , name: 'コニカ オートS カメラ' },
  { q: 'Nikon L35AF compact film camera'                , name: 'ニコン L35AF カメラ' },
  { q: 'Voigtlander Nokton 40mm f1.4 VM'                , name: 'フォクトレンダー ノクトン レンズ' },
  { q: 'Voigtlander Bessa R rangefinder'                , name: 'フォクトレンダー ベッサ カメラ' },
  { q: 'Mamiya 7 II medium format rangefinder'          , name: 'マミヤ 7 カメラ' },
  { q: 'Mamiya RB67 Pro S body'                         , name: 'マミヤ RB67 カメラ' },
  { q: 'Rollei 35 compact film camera'                  , name: 'ローライ 35 カメラ' },
  { q: 'Yashica Electro 35 GSN rangefinder'             , name: 'ヤシカ エレクトロ35 カメラ' },
  { q: 'Fujifilm Klasse compact film camera'            , name: 'フジ クラッセ カメラ' },
  { q: 'Ricoh GR1v compact film camera'                 , name: 'リコー GR1 カメラ' },
  // --- ヴィンテージHi-Fiオーディオ (55) ---
  { q: 'Sansui AU-D907 integrated amplifier'            , name: 'サンスイ AU-D907 アンプ' },
  { q: 'Sansui AU-7900 amplifier'                       , name: 'サンスイ AU-7900 アンプ' },
  { q: 'Sansui AU-555 integrated amplifier'             , name: 'サンスイ AU-555 アンプ' },
  { q: 'Marantz PM-94 integrated amplifier'             , name: 'マランツ PM-94 アンプ' },
  { q: 'Marantz PM-80 amplifier'                        , name: 'マランツ PM-80 アンプ' },
  { q: 'Pioneer A-150 integrated amplifier'             , name: 'パイオニア A-150 アンプ' },
  { q: 'Pioneer SA-8800 amplifier'                      , name: 'パイオニア SA-8800 アンプ' },
  { q: 'Denon PMA-2000 integrated amplifier'            , name: 'デノン PMA-2000 アンプ' },
  { q: 'Denon PMA-1500 amplifier'                       , name: 'デノン PMA-1500 アンプ' },
  { q: 'Luxman L-507 integrated amplifier'              , name: 'ラックスマン L-507 アンプ' },
  { q: 'Luxman L-550 amplifier'                         , name: 'ラックスマン L-550 アンプ' },
  { q: 'Onkyo A-9000R integrated amplifier'             , name: 'オンキヨー A-9000R アンプ' },
  { q: 'Yamaha CA-2000 amplifier'                       , name: 'ヤマハ CA-2000 アンプ' },
  { q: 'Yamaha A-S2000 integrated amplifier'            , name: 'ヤマハ A-S2000 アンプ' },
  { q: 'Accuphase E-202 integrated amplifier'           , name: 'アキュフェーズ E-202 アンプ' },
  { q: 'Technics SL-1200 MK2 turntable'                 , name: 'テクニクス SL-1200 ターンテーブル' },
  { q: 'Technics SL-1210 turntable'                     , name: 'テクニクス SL-1210 ターンテーブル' },
  { q: 'Technics SL-1500 turntable'                     , name: 'テクニクス SL-1500 ターンテーブル' },
  { q: 'Pioneer PLX-1000 turntable'                     , name: 'パイオニア PLX-1000 ターンテーブル' },
  { q: 'Denon DP-1300 turntable'                        , name: 'デノン DP-1300 ターンテーブル' },
  { q: 'Audio-Technica AT-LP120 turntable'              , name: 'オーディオテクニカ AT-LP120 ターンテーブル' },
  { q: 'Audio-Technica VM540ML cartridge'               , name: 'オーディオテクニカ VM540 カートリッジ' },
  { q: 'Audio-Technica AT33 cartridge'                  , name: 'オーディオテクニカ AT33 カートリッジ' },
  { q: 'Audio-Technica AT-VM95 cartridge'               , name: 'オーディオテクニカ VM95 カートリッジ' },
  { q: 'Shure M44-7 cartridge'                          , name: 'シュア M44 カートリッジ' },
  { q: 'Shure V15 cartridge'                            , name: 'シュア V15 カートリッジ' },
  { q: 'Denon DL-103 cartridge'                         , name: 'デノン DL-103 カートリッジ' },
  { q: 'Ortofon SPU cartridge'                          , name: 'オルトフォン SPU カートリッジ' },
  { q: 'Nakamichi Dragon cassette deck'                 , name: 'ナカミチ ドラゴン カセットデッキ' },
  { q: 'Nakamichi 1000 cassette deck'                   , name: 'ナカミチ 1000 カセットデッキ' },
  { q: 'TEAC A-7300 reel to reel'                       , name: 'ティアック A-7300 オープンリール' },
  { q: 'Pioneer RT-707 reel to reel'                    , name: 'パイオニア RT-707 オープンリール' },
  { q: 'Sony TC-K777 cassette deck'                     , name: 'ソニー TC-K777 カセットデッキ' },
  { q: 'Sony WM-D6C Walkman Professional'               , name: 'ソニー WM-D6C ウォークマン' },
  { q: 'Sony TA-F555 integrated amplifier'              , name: 'ソニー TA-F555 アンプ' },
  { q: 'JBL 4312 studio monitor speaker'                , name: 'JBL 4312 スピーカー' },
  { q: 'JBL L100 speaker'                               , name: 'JBL L100 スピーカー' },
  { q: 'Yamaha NS-1000M speaker'                        , name: 'ヤマハ NS-1000M スピーカー' },
  { q: 'Diatone DS-1000 speaker'                        , name: 'ダイヤトーン DS-1000 スピーカー' },
  { q: 'Tannoy speaker vintage'                         , name: 'タンノイ スピーカー' },
  { q: 'Pioneer CS speaker vintage'                     , name: 'パイオニア CS スピーカー' },
  { q: 'Bose 901 speaker'                               , name: 'ボーズ 901 スピーカー' },
  { q: 'Kenwood KT-3300 tuner'                          , name: 'ケンウッド KT チューナー' },
  { q: 'Accuphase T-100 tuner'                          , name: 'アキュフェーズ T チューナー' },
  { q: 'McIntosh MC amplifier vintage'                  , name: 'マッキントッシュ アンプ' },
  { q: 'Audio-Technica AT-HA5000 headphone amplifier'   , name: 'オーディオテクニカ ヘッドホンアンプ' },
  { q: 'STAX SR electrostatic headphone'                , name: 'スタックス ヘッドホン' },
  { q: 'Sennheiser HD650 headphone'                     , name: 'ゼンハイザー HD650 ヘッドホン' },
  { q: 'DENON AH-D5000 headphone'                       , name: 'デノン AH-D5000 ヘッドホン' },
  { q: 'Sansui TU-9900 tuner'                           , name: 'サンスイ TU チューナー' },
  { q: 'Marantz Model 2270 receiver'                    , name: 'マランツ レシーバー ヴィンテージ' },
  { q: 'Pioneer SX-1980 receiver'                       , name: 'パイオニア SX レシーバー' },
  { q: 'Technics SU-V integrated amplifier'             , name: 'テクニクス SU アンプ' },
  { q: 'Onkyo Integra A-927 amplifier'                  , name: 'オンキヨー Integra アンプ' },
  { q: 'Victor TT-101 turntable'                        , name: 'ビクター TT ターンテーブル' },
  // --- ポータブル/ヘッドホン (53) ---
  { q: 'Sony WM-DD9 Walkman'                            , name: 'SONY WM-DD9 ウォークマン' },
  { q: 'Sony WM-EX2000 Walkman'                         , name: 'SONY WM-EX2000 ウォークマン' },
  { q: 'Sony WM-DC2 Walkman'                            , name: 'SONY WM-DC2 ウォークマン' },
  { q: 'Aiwa HS-PX series cassette Walkman'             , name: 'AIWA HS-PX カセット' },
  { q: 'Panasonic RQ-S series cassette Walkman'         , name: 'Panasonic RQ-S カセット' },
  { q: 'Sony WM-101 Walkman'                            , name: 'SONY WM-101 ウォークマン' },
  { q: 'Sony MZ-1 MiniDisc recorder'                    , name: 'SONY MZ-1 MDウォークマン' },
  { q: 'Sony MZ-RH1 Hi-MD recorder'                     , name: 'SONY MZ-RH1 Hi-MD' },
  { q: 'Sony MZ-R909 MiniDisc'                          , name: 'SONY MZ-R909 MD' },
  { q: 'Sony MZ-E10 MiniDisc player'                    , name: 'SONY MZ-E10 MD' },
  { q: 'Sharp MD-DR7 MiniDisc'                          , name: 'SHARP MD-DR MDウォークマン' },
  { q: 'Sony D-50 Discman CD player'                    , name: 'SONY D-50 ディスクマン' },
  { q: 'Sony D-25 Discman'                              , name: 'SONY D-25 ディスクマン' },
  { q: 'Sony Discman D-Z555'                            , name: 'SONY D-Z555 ディスクマン' },
  { q: 'Sony NW-WM1A Walkman'                           , name: 'SONY NW-WM1A ウォークマン' },
  { q: 'Sony NW-ZX300 Walkman'                          , name: 'SONY NW-ZX300 ウォークマン' },
  { q: 'Sony NW-A55 Walkman'                            , name: 'SONY NW-A55 ウォークマン' },
  { q: 'Sony MDR-Z1R headphones'                        , name: 'SONY MDR-Z1R ヘッドホン' },
  { q: 'Sony MDR-7506 headphones'                       , name: 'SONY MDR-7506 ヘッドホン' },
  { q: 'Sony MDR-CD900ST headphones'                    , name: 'SONY MDR-CD900ST ヘッドホン' },
  { q: 'Sony MDR-R10 headphones'                        , name: 'SONY MDR-R10 ヘッドホン' },
  { q: 'Sony MDR-V6 headphones'                         , name: 'SONY MDR-V6 ヘッドホン' },
  { q: 'Audio-Technica ATH-M50x headphones'             , name: 'audio-technica ATH-M50x ヘッドホン' },
  { q: 'Audio-Technica ATH-W1000 headphones'            , name: 'audio-technica ATH-W1000 ヘッドホン' },
  { q: 'Audio-Technica ATH-AD2000 headphones'           , name: 'audio-technica ATH-AD2000 ヘッドホン' },
  { q: 'Audio-Technica ATH-ESW9 headphones'             , name: 'audio-technica ATH-ESW9 ヘッドホン' },
  { q: 'Sennheiser HD600 headphones'                    , name: 'ゼンハイザー HD600 ヘッドホン' },
  { q: 'Sennheiser HD800S headphones'                   , name: 'ゼンハイザー HD800 ヘッドホン' },
  { q: 'Sennheiser HD25 headphones'                     , name: 'ゼンハイザー HD25 ヘッドホン' },
  { q: 'Sennheiser Momentum headphones'                 , name: 'ゼンハイザー MOMENTUM ヘッドホン' },
  { q: 'Beyerdynamic DT770 Pro headphones'              , name: 'ベイヤーダイナミック DT770 ヘッドホン' },
  { q: 'Beyerdynamic DT880 headphones'                  , name: 'ベイヤーダイナミック DT880 ヘッドホン' },
  { q: 'Beyerdynamic DT990 Pro headphones'              , name: 'ベイヤーダイナミック DT990 ヘッドホン' },
  { q: 'Beyerdynamic T1 headphones'                     , name: 'ベイヤーダイナミック T1 ヘッドホン' },
  { q: 'AKG K701 headphones'                            , name: 'AKG K701 ヘッドホン' },
  { q: 'AKG K240 Studio headphones'                     , name: 'AKG K240 ヘッドホン' },
  { q: 'AKG K712 Pro headphones'                        , name: 'AKG K712 ヘッドホン' },
  { q: 'Grado SR80 headphones'                          , name: 'グラド SR80 ヘッドホン' },
  { q: 'Grado RS1 headphones'                           , name: 'グラド RS1 ヘッドホン' },
  { q: 'Bose QuietComfort 35 headphones'                , name: 'BOSE QuietComfort 35 ヘッドホン' },
  { q: 'Sony WH-1000XM4 headphones'                     , name: 'SONY WH-1000XM4 ヘッドホン' },
  { q: 'STAX SR-007 electrostatic headphones'           , name: 'STAX SR-007 ヘッドホン' },
  { q: 'STAX SR-Lambda earspeaker'                      , name: 'STAX SR-Lambda ヘッドホン' },
  { q: 'Fostex T50RP headphones'                        , name: 'FOSTEX T50RP ヘッドホン' },
  { q: 'Pioneer SE-Master1 headphones'                  , name: 'Pioneer SE-MONITOR ヘッドホン' },
  { q: 'Koss Porta Pro headphones'                      , name: 'KOSS Porta Pro ヘッドホン' },
  { q: 'Etymotic ER4 earphones'                         , name: 'Etymotic ER4 イヤホン' },
  { q: 'Shure SE846 earphones'                          , name: 'SHURE SE846 イヤホン' },
  { q: 'Campfire Audio Andromeda earphones'             , name: 'Campfire Andromeda イヤホン' },
  { q: 'Audeze LCD-2 planar headphones'                 , name: 'Audeze LCD-2 ヘッドホン' },
  { q: 'HiFiMan Sundara headphones'                     , name: 'HiFiMAN Sundara ヘッドホン' },
  { q: 'Final Audio E5000 earphones'                    , name: 'final E5000 イヤホン' },
  { q: 'Sony MDR-EX1000 earphones'                      , name: 'SONY MDR-EX1000 イヤホン' },
  // --- レトロゲーム機・周辺 (55) ---
  { q: 'Nintendo Famicom HVC-001 console'               , name: '任天堂 ファミコン HVC-001 本体' },
  { q: 'Nintendo Super Famicom SHVC-001 console'        , name: '任天堂 スーパーファミコン SHVC 本体' },
  { q: 'Nintendo AV Famicom HVC-101 console'            , name: '任天堂 ニューファミコン AV HVC-101 本体' },
  { q: 'Nintendo Famicom Disk System HVC-022'           , name: '任天堂 ディスクシステム HVC-022 本体' },
  { q: 'Nintendo Super Famicom controller SHVC-005'     , name: 'スーパーファミコン コントローラー SHVC-005' },
  { q: 'Nintendo 64 NUS-001 console'                    , name: '任天堂 NINTENDO64 NUS-001 本体' },
  { q: 'Nintendo 64 controller NUS-005'                 , name: 'NINTENDO64 コントローラー NUS-005' },
  { q: 'Nintendo 64 Expansion Pak NUS-007'              , name: 'NINTENDO64 メモリー拡張パック NUS-007' },
  { q: 'Nintendo GameCube DOL-001 console'              , name: 'ニンテンドー ゲームキューブ DOL-001 本体' },
  { q: 'Nintendo GameCube controller DOL-003'           , name: 'ゲームキューブ コントローラー DOL-003' },
  { q: 'Nintendo GameCube Game Boy Player DOL-017'      , name: 'ゲームキューブ ゲームボーイプレーヤー DOL-017' },
  { q: 'Game Boy Advance SP AGS-101 backlit'            , name: 'ゲームボーイアドバンス SP AGS-101 本体' },
  { q: 'Game Boy Advance AGB-001 console'               , name: 'ゲームボーイアドバンス AGB-001 本体' },
  { q: 'Game Boy Color CGB-001 console'                 , name: 'ゲームボーイカラー CGB-001 本体' },
  { q: 'Game Boy Micro OXY-001 console'                 , name: 'ゲームボーイミクロ OXY-001 本体' },
  { q: 'Game Boy DMG-01 original console'               , name: 'ゲームボーイ DMG-01 本体' },
  { q: 'Nintendo DS Lite USG-001 console'               , name: 'ニンテンドーDS Lite USG-001 本体' },
  { q: 'Nintendo Game Boy Light MGB-101'                , name: 'ゲームボーイライト MGB-101 本体' },
  { q: 'Virtual Boy Nintendo console'                   , name: '任天堂 バーチャルボーイ 本体' },
  { q: 'Sega Saturn HST-3200 console'                   , name: 'セガ サターン HST-3200 本体' },
  { q: 'Sega Saturn controller white model 2'           , name: 'セガ サターン コントローラー 純正' },
  { q: 'Sega Dreamcast HKT-3000 console'                , name: 'セガ ドリームキャスト HKT-3000 本体' },
  { q: 'Sega Dreamcast controller HKT-7700'             , name: 'ドリームキャスト コントローラー HKT-7700' },
  { q: 'Sega Dreamcast VMU HKT-7000'                    , name: 'ドリームキャスト ビジュアルメモリ VMU' },
  { q: 'Sega Mega Drive console Japanese'               , name: 'セガ メガドライブ 本体' },
  { q: 'Sega Mega Drive 2 console'                      , name: 'セガ メガドライブ2 本体' },
  { q: 'Sega Mega Drive controller 6 button'            , name: 'メガドライブ コントローラー 6ボタン' },
  { q: 'Sega Game Gear handheld console'                , name: 'セガ ゲームギア 本体' },
  { q: 'Sega Mega CD console'                           , name: 'セガ メガCD 本体' },
  { q: 'Sega 32X console'                               , name: 'セガ スーパー32X 本体' },
  { q: 'Sega Saturn Virtua Stick controller'            , name: 'セガ サターン バーチャスティック' },
  { q: 'Sony PlayStation SCPH-1000 console'             , name: 'ソニー プレイステーション SCPH-1000 本体' },
  { q: 'Sony PlayStation SCPH-5500 console'             , name: 'プレイステーション SCPH-5500 本体' },
  { q: 'Sony PSone SCPH-100 console'                    , name: 'ソニー PSone SCPH-100 本体' },
  { q: 'Sony PlayStation DualShock SCPH-1200'           , name: 'プレイステーション デュアルショック SCPH-1200' },
  { q: 'Sony PlayStation 2 SCPH-30000 console'          , name: 'プレイステーション2 SCPH-30000 本体' },
  { q: 'Sony PlayStation 2 slim SCPH-70000'             , name: 'プレイステーション2 SCPH-70000 本体' },
  { q: 'Sony PS2 DualShock 2 SCPH-10010'                , name: 'PS2 デュアルショック2 コントローラー' },
  { q: 'Sony PocketStation SCPH-4000'                   , name: 'ソニー ポケットステーション SCPH-4000' },
  { q: 'Sony PSP-1000 console'                          , name: 'ソニー PSP-1000 本体' },
  { q: 'Sony PSP-3000 console'                          , name: 'ソニー PSP-3000 本体' },
  { q: 'Sony PSP Go PSP-N1000'                          , name: 'ソニー PSP go PSP-N1000 本体' },
  { q: 'Sony PS Vita PCH-1000 console'                  , name: 'PS Vita PCH-1000 本体' },
  { q: 'NEC PC Engine core grafx console'               , name: 'NEC PCエンジン コアグラフィックス 本体' },
  { q: 'NEC PC Engine Duo console'                      , name: 'NEC PCエンジン Duo 本体' },
  { q: 'NEC PC Engine GT handheld'                      , name: 'NEC PCエンジンGT 本体' },
  { q: 'SNK Neo Geo AES console'                        , name: 'SNK ネオジオ AES 本体' },
  { q: 'SNK Neo Geo Pocket Color console'               , name: 'SNK ネオジオポケットカラー 本体' },
  { q: 'SNK Neo Geo CD console'                         , name: 'SNK ネオジオCD 本体' },
  { q: 'Bandai WonderSwan Color console'                , name: 'バンダイ ワンダースワンカラー 本体' },
  { q: 'Nintendo Famicom Twin AN-505 Sharp'             , name: 'シャープ ツインファミコン AN-505 本体' },
  { q: 'Nintendo Super Famicom Jr SHVC-101'             , name: 'スーパーファミコンジュニア SHVC-101 本体' },
  { q: 'Sega Saturn controller pad SS Asci'             , name: 'セガ サターン アスキーパッド' },
  { q: 'Sony PS1 multitap SCPH-1070'                    , name: 'プレイステーション マルチタップ SCPH-1070' },
  { q: 'Nintendo SNES Super Game Boy SHVC-027'          , name: 'スーパーゲームボーイ SHVC-027 本体' },
  // --- 楽器・エフェクター (55) ---
  { q: 'Boss DS-1 distortion'                           , name: 'BOSS DS-1 エフェクター' },
  { q: 'Boss SD-1 super overdrive'                      , name: 'BOSS SD-1 エフェクター' },
  { q: 'Boss BD-2 blues driver'                         , name: 'BOSS BD-2 エフェクター' },
  { q: 'Boss DD-3 digital delay'                        , name: 'BOSS DD-3 ディレイ エフェクター' },
  { q: 'Boss DD-7 digital delay'                        , name: 'BOSS DD-7 ディレイ エフェクター' },
  { q: 'Boss CE-2 chorus'                               , name: 'BOSS CE-2 コーラス エフェクター' },
  { q: 'Boss RV-6 reverb'                               , name: 'BOSS RV-6 リバーブ エフェクター' },
  { q: 'Boss MT-2 metal zone'                           , name: 'BOSS MT-2 エフェクター' },
  { q: 'Boss OC-3 super octave'                         , name: 'BOSS OC-3 エフェクター' },
  { q: 'Boss TU-3 tuner pedal'                          , name: 'BOSS TU-3 チューナー エフェクター' },
  { q: 'Ibanez TS9 tube screamer'                       , name: 'Ibanez TS9 エフェクター' },
  { q: 'Ibanez TS808 tube screamer'                     , name: 'Ibanez TS808 エフェクター' },
  { q: 'Ibanez TS Mini tube screamer'                   , name: 'Ibanez TS Mini エフェクター' },
  { q: 'Electro-Harmonix Big Muff Pi'                   , name: 'Electro-Harmonix Big Muff エフェクター' },
  { q: 'Electro-Harmonix Nano Big Muff'                 , name: 'Electro-Harmonix Nano Big Muff' },
  { q: 'Electro-Harmonix Memory Boy delay'              , name: 'Electro-Harmonix Memory Boy' },
  { q: 'Electro-Harmonix POG2 octave'                   , name: 'Electro-Harmonix POG2' },
  { q: 'MXR Phase 90'                                   , name: 'MXR Phase 90 エフェクター' },
  { q: 'MXR Carbon Copy delay'                          , name: 'MXR Carbon Copy エフェクター' },
  { q: 'MXR Dyna Comp compressor'                       , name: 'MXR Dyna Comp エフェクター' },
  { q: 'MXR Micro Amp boost'                            , name: 'MXR Micro Amp エフェクター' },
  { q: 'Strymon BigSky reverb'                          , name: 'Strymon BigSky エフェクター' },
  { q: 'Strymon Timeline delay'                         , name: 'Strymon Timeline エフェクター' },
  { q: 'Strymon El Capistan delay'                      , name: 'Strymon El Capistan エフェクター' },
  { q: 'ProCo RAT 2 distortion'                         , name: 'ProCo RAT エフェクター' },
  { q: 'Fulltone OCD overdrive'                         , name: 'Fulltone OCD エフェクター' },
  { q: 'Roland Boss RC-1 loop station'                  , name: 'BOSS RC-1 ルーパー エフェクター' },
  { q: 'Roland Boss RC-3 loop station'                  , name: 'BOSS RC-3 ルーパー エフェクター' },
  { q: 'Roland JC-120 amp'                              , name: 'Roland JC-120 アンプ' },
  { q: 'Roland Juno-106 synthesizer'                    , name: 'Roland Juno-106 シンセ' },
  { q: 'Roland SH-101 synthesizer'                      , name: 'Roland SH-101 シンセ' },
  { q: 'Roland TR-8S drum machine'                      , name: 'Roland TR-8S ドラムマシン' },
  { q: 'Roland Boutique JU-06'                          , name: 'Roland Boutique JU-06 シンセ' },
  { q: 'Korg Volca Keys synthesizer'                    , name: 'Korg Volca シンセ' },
  { q: 'Korg Minilogue synthesizer'                     , name: 'Korg Minilogue シンセ' },
  { q: 'Korg MS-20 mini synthesizer'                    , name: 'Korg MS-20 シンセ' },
  { q: 'Korg Monotron analog synth'                     , name: 'Korg Monotron シンセ' },
  { q: 'Yamaha Reface DX synthesizer'                   , name: 'Yamaha Reface シンセ' },
  { q: 'Yamaha DX7 synthesizer'                         , name: 'Yamaha DX7 シンセ' },
  { q: 'Focusrite Scarlett 2i2 interface'               , name: 'Focusrite Scarlett 2i2 オーディオインターフェース' },
  { q: 'Focusrite Scarlett Solo interface'              , name: 'Focusrite Scarlett Solo インターフェース' },
  { q: 'Steinberg UR22C audio interface'                , name: 'Steinberg UR22 オーディオインターフェース' },
  { q: 'Universal Audio Apollo Twin'                    , name: 'Universal Audio Apollo オーディオインターフェース' },
  { q: 'Boss GT-1 guitar processor'                     , name: 'BOSS GT-1 マルチエフェクター' },
  { q: 'Line 6 HX Stomp multi effects'                  , name: 'Line 6 HX Stomp エフェクター' },
  { q: 'Line 6 POD HD500X'                              , name: 'Line 6 POD HD500 マルチエフェクター' },
  { q: 'Zoom G3n multi effects'                         , name: 'Zoom G3 マルチエフェクター' },
  { q: 'Boss CS-3 compression sustainer'                , name: 'BOSS CS-3 エフェクター' },
  { q: 'Boss RV-5 digital reverb'                       , name: 'BOSS RV-5 リバーブ エフェクター' },
  { q: 'Boss OD-3 overdrive'                            , name: 'BOSS OD-3 エフェクター' },
  { q: 'Walrus Audio Julia chorus'                      , name: 'Walrus Audio Julia エフェクター' },
  { q: 'JHS Morning Glory overdrive'                    , name: 'JHS Morning Glory エフェクター' },
  { q: 'Wampler Tumnus overdrive'                       , name: 'Wampler Tumnus エフェクター' },
  { q: 'Empress Effects Compressor'                     , name: 'Empress Compressor エフェクター' },
  { q: 'Boss DM-2W delay waza craft'                    , name: 'BOSS DM-2W エフェクター' },
  // --- 電動工具(本体のみ) (54) ---
  { q: 'Makita TD172D impact driver body only'          , name: 'マキタ TD172D インパクトドライバー' },
  { q: 'Makita TD171D impact driver tool only'          , name: 'マキタ TD171D インパクトドライバー' },
  { q: 'Makita TD160D impact driver body only'          , name: 'マキタ TD160D インパクトドライバー' },
  { q: 'Makita TD149D impact driver tool only'          , name: 'マキタ TD149D インパクトドライバー' },
  { q: 'Makita DTD172 impact driver body only'          , name: 'マキタ DTD172 インパクトドライバー' },
  { q: 'Makita DTD171 brushless impact driver tool only', name: 'マキタ DTD171 インパクトドライバー' },
  { q: 'Makita DTD153 impact driver body only'          , name: 'マキタ DTD153 インパクトドライバー' },
  { q: 'Makita TD002G 40V impact driver body only'      , name: 'マキタ TD002G インパクトドライバー' },
  { q: 'Makita DF484D driver drill tool only'           , name: 'マキタ DF484D ドライバドリル' },
  { q: 'Makita DF333D driver drill body only'           , name: 'マキタ DF333D ドライバドリル' },
  { q: 'Makita HP486D hammer driver drill body only'    , name: 'マキタ HP486D 震動ドライバドリル' },
  { q: 'Makita HP331D hammer drill tool only'           , name: 'マキタ HP331D 震動ドライバドリル' },
  { q: 'Makita HS474D circular saw body only'           , name: 'マキタ HS474D 丸ノコ' },
  { q: 'Makita HS001G 40V circular saw body only'       , name: 'マキタ HS001G 丸ノコ' },
  { q: 'Makita GA404D angle grinder body only'          , name: 'マキタ GA404D ディスクグラインダー' },
  { q: 'Makita DGA404 angle grinder tool only'          , name: 'マキタ DGA404 ディスクグラインダー' },
  { q: 'Makita JR187D recipro saw body only'            , name: 'マキタ JR187D レシプロソー' },
  { q: 'Makita DUH507 hedge trimmer tool only'          , name: 'マキタ DUH507 ヘッジトリマー' },
  { q: 'Makita DUR368 brush cutter body only'           , name: 'マキタ DUR368 草刈機' },
  { q: 'Makita DUB184 blower body only'                 , name: 'マキタ DUB184 ブロワー' },
  { q: 'Makita TW001G impact wrench body only'          , name: 'マキタ TW001G インパクトレンチ' },
  { q: 'Makita TW300D impact wrench tool only'          , name: 'マキタ TW300D インパクトレンチ' },
  { q: 'Makita DTW285 impact wrench body only'          , name: 'マキタ DTW285 インパクトレンチ' },
  { q: 'Makita CL182 vacuum cleaner body only'          , name: 'マキタ CL182 充電クリーナー' },
  { q: 'Makita DPB182 band saw body only'               , name: 'マキタ DPB182 バンドソー' },
  { q: 'Makita DML809 work light body only'             , name: 'マキタ DML809 充電ライト' },
  { q: 'Makita DRT50 trimmer router body only'          , name: 'マキタ DRT50 トリマ' },
  { q: 'Makita DLS713 miter saw body only'              , name: 'マキタ DLS713 卓上スライド丸ノコ' },
  { q: 'Makita DHR243 rotary hammer body only'          , name: 'マキタ DHR243 ハンマードリル' },
  { q: 'Makita DHR171 rotary hammer tool only'          , name: 'マキタ DHR171 ハンマードリル' },
  { q: 'Makita DTS141 oil pulse driver body only'       , name: 'マキタ DTS141 ソフトインパクト' },
  { q: 'Makita DFS452 screwdriver body only'            , name: 'マキタ DFS452 スクリュードライバ' },
  { q: 'HiKOKI WH36DC impact driver body only'          , name: 'ハイコーキ WH36DC インパクトドライバー' },
  { q: 'HiKOKI WH36DD impact driver tool only'          , name: 'ハイコーキ WH36DD インパクトドライバー' },
  { q: 'HiKOKI WH18DD impact driver body only'          , name: 'ハイコーキ WH18DD インパクトドライバー' },
  { q: 'HiKOKI WH14DDL impact driver body only'         , name: 'ハイコーキ WH14DDL インパクトドライバー' },
  { q: 'HiKOKI DV18DD hammer drill body only'           , name: 'ハイコーキ DV18DD 震動ドライバドリル' },
  { q: 'HiKOKI DS18DD driver drill tool only'           , name: 'ハイコーキ DS18DD ドライバドリル' },
  { q: 'HiKOKI C3606DA circular saw body only'          , name: 'ハイコーキ C3606DA 丸ノコ' },
  { q: 'HiKOKI C1806DA circular saw tool only'          , name: 'ハイコーキ C1806DA 丸ノコ' },
  { q: 'HiKOKI G3613DA angle grinder body only'         , name: 'ハイコーキ G3613DA ディスクグラインダー' },
  { q: 'HiKOKI CR36DA recipro saw body only'            , name: 'ハイコーキ CR36DA レシプロソー' },
  { q: 'HiKOKI WR36DE impact wrench body only'          , name: 'ハイコーキ WR36DE インパクトレンチ' },
  { q: 'HiKOKI WR18DF impact wrench tool only'          , name: 'ハイコーキ WR18DF インパクトレンチ' },
  { q: 'HiKOKI DH36DPA rotary hammer body only'         , name: 'ハイコーキ DH36DPA ハンマードリル' },
  { q: 'HiKOKI RB36DB blower body only'                 , name: 'ハイコーキ RB36DB ブロワー' },
  { q: 'HiKOKI UB18DD work light body only'             , name: 'ハイコーキ UB18DD 充電ライト' },
  { q: 'HiKOKI CG36DA brush cutter body only'           , name: 'ハイコーキ CG36DA 草刈機' },
  { q: 'HiKOKI M3608DA router body only'                , name: 'ハイコーキ M3608DA トリマ' },
  { q: 'HiKOKI FWH14DGL impact driver tool only'        , name: 'ハイコーキ FWH14DGL インパクトドライバー' },
  { q: 'Makita DTD157 impact driver body only'          , name: 'マキタ DTD157 インパクトドライバー' },
  { q: 'Makita TD173D impact driver body only'          , name: 'マキタ TD173D インパクトドライバー' },
  { q: 'HiKOKI WH36DA impact driver body only'          , name: 'ハイコーキ WH36DA インパクトドライバー' },
  { q: 'Makita DDF485 driver drill body only'           , name: 'マキタ DDF485 ドライバドリル' },

  // ===== 【時計・供給拡大 2026-07-04・②】OFFモール時計2.5万件に対しカタログ88件＝母数を厚くする（既存174クエリと非重複）。
  //   q=eBay英語(国際refで落札タイトルに出る型番) / name=ハードオフ検索語(腕時計含む)。型番がeBayに出る＝確定できるモデルを優先。=====
  // --- セイコー5スポーツ SRPD 色番（SKX後継・eBayで人気＝確定しやすい） ---
  { q: 'Seiko 5 Sports SRPD51 black gold automatic japan'   , name: 'セイコー5スポーツ 腕時計 SRPD51' },
  { q: 'Seiko 5 Sports SRPD53 blue automatic japan'         , name: 'セイコー5スポーツ 腕時計 SRPD53' },
  { q: 'Seiko 5 Sports SRPD55 silver blue automatic japan'  , name: 'セイコー5スポーツ 腕時計 SRPD55' },
  { q: 'Seiko 5 Sports SRPD65 blue automatic japan'         , name: 'セイコー5スポーツ 腕時計 SRPD65' },
  { q: 'Seiko 5 Sports SRPD85 orange automatic japan'       , name: 'セイコー5スポーツ 腕時計 SRPD85' },
  // --- セイコー プロスペックス（ダイバー・確定強い） ---
  { q: 'Seiko Prospex 62MAS SPB149 blue automatic japan'    , name: 'セイコー プロスペックス 腕時計 SPB149' },
  { q: 'Seiko Prospex 62MAS SPB147 automatic japan'         , name: 'セイコー プロスペックス 腕時計 SPB147' },
  { q: 'Seiko Prospex Sumo SPB185 automatic japan'          , name: 'セイコー プロスペックス スモウ 腕時計 SPB185' },
  { q: 'Seiko Prospex Sumo SPB187 blue automatic japan'     , name: 'セイコー プロスペックス スモウ 腕時計 SPB187' },
  { q: 'Seiko Prospex 62MAS SPB317 automatic japan'         , name: 'セイコー プロスペックス 腕時計 SPB317' },
  { q: 'Seiko Prospex Turtle SRPE93 blue automatic japan'   , name: 'セイコー プロスペックス タートル 腕時計 SRPE93' },
  { q: 'Seiko Prospex Solar Diver SNE573'                   , name: 'セイコー プロスペックス 腕時計 SNE573' },
  { q: 'Seiko King Seiko SPB285 automatic japan'            , name: 'キングセイコー 腕時計 SPB285' },
  // --- グランドセイコー（未収録・高額かつ型番がeBayに出る＝確定しやすい） ---
  { q: 'Grand Seiko SBGA211 Snowflake Spring Drive'         , name: 'グランドセイコー 腕時計 SBGA211' },
  { q: 'Grand Seiko SBGX261 quartz'                         , name: 'グランドセイコー 腕時計 SBGX261' },
  { q: 'Grand Seiko SBGA413 Spring Drive Shunbun'           , name: 'グランドセイコー 腕時計 SBGA413' },
  { q: 'Grand Seiko SBGN005 GMT quartz'                     , name: 'グランドセイコー 腕時計 SBGN005' },
  // --- G-SHOCK 新ライン（既存と非重複） ---
  { q: 'Casio G-Shock GBD-200 running black'                , name: 'カシオ Gショック 腕時計 GBD-200' },
  { q: 'Casio G-Shock GBA-900 mobile link'                  , name: 'カシオ Gショック 腕時計 GBA-900' },
  { q: 'Casio G-Shock DW-6900'                              , name: 'カシオ Gショック 腕時計 DW-6900' },
  { q: 'Casio G-Shock GA-B001'                              , name: 'カシオ Gショック 腕時計 GA-B001' },
  { q: 'Casio G-Shock GA-2200'                              , name: 'カシオ Gショック 腕時計 GA-2200' },
  { q: 'Casio G-Steel GST-B500 solar'                       , name: 'カシオ Gショック Gスチール 腕時計 GST-B500' },
  { q: 'Casio G-Shock Mudmaster GWG-2000 carbon'            , name: 'カシオ Gショック マッドマスター 腕時計 GWG-2000' },
  // --- シチズン（国際的に型番が出るモデル＝FUGU/ECOZILLA等） ---
  { q: 'Citizen Promaster Fugu NY0040 automatic diver'      , name: 'シチズン プロマスター フグ 腕時計 NY0040' },
  { q: 'Citizen Promaster BN0151 eco-drive diver'           , name: 'シチズン プロマスター 腕時計 BN0151' },
  { q: 'Citizen Promaster Ecozilla BJ8050 eco-drive'        , name: 'シチズン プロマスター エコジラ 腕時計 BJ8050' },
  // --- カシオ クラシック/レディース（回転が速い定番） ---
  { q: 'Casio vintage LA670WA gold digital'                 , name: 'カシオ 腕時計 LA670' },
  { q: 'Casio MQ-24 analog'                                 , name: 'カシオ 腕時計 MQ-24' },
  { q: 'Casio W-800H digital'                               , name: 'カシオ 腕時計 W-800' },
  // --- ティソ（既存と非重複） ---
  { q: 'Tissot Supersport Chrono'                           , name: 'ティソ スーパースポーツ 腕時計' },
];

// 【SSOT】ハードオフ中古カタログ対象ジャンル（発掘フィルタ＝ebaySoldWorker と build＝buildUsedSampleFromCache の双方が使う）。
//   「型番がeBayタイトルに出る×ハードオフが中古で扱う×輸出できる」ジャンルだけを通す。
//   新品sealed系(TCG/フィギュア/ゲームソフト/コスメ/プラモ/ぬいぐるみ等)は中古×型番照合と相性が悪いので含めない。
// ハードオフ中古の本領＝「型番がeBayタイトルに出る×ハードオフが中古で扱う×輸出可(非危険物)」ジャンル。
// 2026-06-28 供給拡大のため時計/オーディオ中心→カメラ・レンズ/レトロゲーム/楽器・エフェクター/電動工具へ大幅拡張。
// カテゴリ名(ebayQueries の name)はこのどれかに必ず当たること＝当たらないと loadCategories で捨てられる。
export const USED_GENRE_KW =
  /腕時計|ウォッチ|セイコー|シチズン|カシオ|Gショック|G-?SHOCK|オリエント|オシアナス|アテッサ|プロマスター|エディフィス|プロトレック|ロイヤルAE|F91W|ダイバー|クロノグラフ|watch|ハミルトン|タイメックス|スウォッチ|ウォークマン|ヘッドホン|ヘッドフォン|イヤホン|アンプ|スピーカー|ターンテーブル|レコードプレーヤー|カセットデッキ|MDプレーヤー|カートリッジ|iPod|オーディオ|テクニクス|パイオニア|マランツ|サンスイ|デノン|オンキヨー|オーディオテクニカ|ゼンハイザー|レンズ|フィルムカメラ|一眼|カメラ|デジカメ|ミラーレス|キヤノン|キャノン|ニコン|フジフイルム|富士フイルム|オリンパス|ペンタックス|ライカ|コンタックス|本体|ファミコン|スーパーファミコン|ニンテンドー|任天堂|ゲームボーイ|ゲームキューブ|セガ|サターン|ドリームキャスト|メガドライブ|プレイステーション|プレステ|PSP|Vita|ゲーム機|コントローラー|エフェクター|ギター|ベース|シンセ|シンセサイザー|キーボード|オーディオインターフェース|ドラムマシン|電動工具|インパクトドライバー|ドリル|マキタ|HiKOKI|ハイコーキ|ソニー|パナソニック|LUMIX|シグマ|タムロン|ボディ|チューナー|オープンリール|ティアック|ケンウッド|アキュフェーズ|ラックスマン|デッキ|SONY|Panasonic|AIWA|アイワ|ディスクマン|カセット|Hi-MD|Electro-Harmonix|Focusrite|インターフェース|Roland|Korg|Ibanez|Strymon|NINTENDO|メモリー拡張/i;
